= JEP-205: Declarative Data Binding
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| JEP
| 205

| Title
| Declarative Data Binding

| Sponsor
| link:https://github.com/ndeloof[ndeloof]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Standards

| Created
| 2018-06-08

// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

Jenkins web UI relies on Stapler framework, which uses a JSON payload to bind web form inputs
to Java model. Processing this payload to match Java model constraint use to be implemented with
human written code. This is both annoying to write and prevents automatic discovery of this model
by third party tools, like Jenkins Pipeline or Configuration-as-Code (JEP-201).

This document describe how we can rely on annotation on code to implement those exact same
constraints in a declarative way, making developer life easier, and enabling better tooling.

== Specification

=== Meta-Model annotations

Declarative Data Binding defines annotations for data-binding. This is an opt-in mechanism, an
arbitrary class can't be used for DataBinding.

Existing `@DataBoundSetter` is supported, but we introduce additional `@DataBound` annotation.

Like `@DataBoundSetter`, `@DataBound` can be applied to method or field, but also to a class. Doing so
all (non transient) fields and setters are considered to be used for data-binding. Also, even being public,
annotated element is marked `@Restricted(NoExternalUse)` to avoid reuse by third party components,
as a DataBound component expects a specific lifecycle (instantiation, data injection, validation, post-construction)
and shouldn't be reused outside this specific context, until explicitely enabled by developer.

JSR-303 "Bean Validation" annotations are supported both on fields and setter parameter to define constraints
on the data-bound model.

`@Trim` annotation allows to handle a common development pattern to trim strings and convert empty strings
to null to reflect unset values. This annotation enable transformation on the payload before value is injected,
so developer don't have to handle this.

Some may argue it is better to trim to empty strintgs, to prevent `NullPointerException`. Our reasoning is that
an empty string has no meaning, so we prefer to enforce a default value is set, so:

`@DefaultValue` annotation allows to declare properties value when none is submitted in
json payload, or value is `null` (possibly after being trimmed).

=== UI data-binding

Jelly tags used by Jenkins to build configuration forms for a Data Bound component get extended so they read the
DataBoundModel for target type and adjust the produced HTML element accordingly, reflecting data model constraints.

Typically, Bean Validation annotations are used to tweak the HTML `<input>` element with adequate HTML5 attributes.
`DefaultValue` annotation is also used to set initial value when form is used to create a new instance.

So for sample, taking a DataBound field defined as:
```java
    @Positive @DefaultValue("1")
    private int numExecutors;
```

using a minimal `<f:textbox>` jelly form element, will get following HTML element generated without any extra developer effort:
```xml
   <input type="number" min="1" value="1" name="_.numExecutors"/>
```

== Motivation

link:http://stapler.kohsuke.org/[Stapler] framework is the backbone of Jenkins web UI. It is designed to
offer data-binding from a (jelly or groovy) web view to Java model. For this purpose, a JSON payload
is sent when a configuration form is submitted, and Stapler converts this back to java model classes
using a "DataBound" constructor and optional setters.

This mechanism offers some discoverable data model on the Java API : the DataBound constructor and setters
let us know about the name and types of the expected payload. This is the basis for Configuration-as-Code
(JEP-201). But this model is pretty poor: the only constraint we know on attribute is the expected type.
In many cases, some additional requirement are checked with human-written code. Typically, parameters get
trimmed, checked for being empty or null, ensure value belongs to some range or match a pattern, etc.

On the other hand, the web UI form is built by accessing live Java model data using read methods, being
converted to plain strings. It's up to the plugin developer to define constraints on the html elements
so they reflect the data model.

Generally speaking, with every single line of human-written code to handle data binding we introduce
development effort / risk to introduce bugs, and we block opportunity for third-party components to discover
the underlying data model.


== Reasoning

Annotations have been used extensively by many frameworks to define metadata on data models expressed as
Java classes. Typically, link:https://jcp.org/en/jsr/detail?id=338[Java Persistence API] defines
how a Java object can be mapped to a database, while link:https://jcp.org/en/jsr/detail?id=222[JAXB] defines
annotations to customize how java attributes will be mapped to xml elements.

This JEP is about introducing support for annotation-based declarative data binding. A DataBound Jenkins
component would only rely on annotations to define how attributes are bound to JSON payload from web forms,
including validation constraints. This would have two major benefits:

1. Plugin developers would need to write less code, and use standard annotations they probably already know
from other Java related projects.

2. Constraints on the data model can be introspected. This will allow third party tools to adjust their
behavior accordingly. A good candidate for this is Configuration-as-Code (JEP-201). Jelly tags used to
compose the web UI also could introspect those annotations. For example, if some attribute is a number and
has to be positive, `<input type='number' 'min=0'>` html 5 element would be automatically generated.

Both https://github.com/jenkinsci/structs-plugin[structs plugin] and
https://github.com/jenkinsci/configuration-as-code-plugin[configuration-as-code plugin] do re-implement
Stapler's DataBound component lifecycle and as such will also require to be updated to implement this JEP.

JEP 205 do include definition of a meta-model API so such components don't have to re-implement this logic
and ensure they always are up to date with Stapler version being used, and expectation from plugin developers.

==== Relying on Bean Validation

link:http://beanvalidation.org/2.0/spec/[Bean Validation] is an annotation-based framework designed for
generic usage defining constraints validation on data in a Java model. It allows definition of model
constraints in a fully declarative way, and defines the mechanism to run validation and discover violations.

Bean Validation also is extensible by developers who can define custom annotations and rules to implement
them.

Selected implementation for Bean Validation 2.0 is the reference implementation hibernate-validator, until
some dependency issue is detected and blocks this choice.

==== Relying on JSON-B

link:http://json-b.net/[Json-B] (JSR 367) is the approved specification for JSON binding. It has been highly
inspired by link:https://github.com/FasterXML/jackson[Jackson] and defines the exact binding requirements
Stapler implement, but relying on standard annotations (vs custom `@DataBoundConstructor`.

As Stapler will still need to support legacy data-binding for backward compatibility, we can't just replace
it with a Json-B implementation. We could consider adding support for such standard annotations as
alternatives to stapler specific ones. But on the other way a Jenkins databound component is nothing like
a reusable piece of software, and the
link:https://javadoc.io/doc/javax.json.bind/javax.json.bind-api/1.0[Json-B annotations]
are mostly designed to tune Java to Json conversion, not providing huge benefits.

==== Field vs Setter injection

An endless debate for annotation based framework is about using annotations on private fields, vs using them
on accessors. Most frameworks support both as there's no single answer to this debate.

On one side, injection on private field require Java reflexion to unlock private field accessibility (or
use Variable Handles on java 9+). It makes testing harder as there's no trivial way to mock or instantiate
the target component.

On the other side, setter injection require some boilerplate code being added to codebase, and don't prevent
external component to create an instance without invoking such setters, resulting in misconfigured component.
Same applies to any `@PostConstruct` initializer method.

Generally speaking, a component designed for data-binding can't guarantee it exposes a safe API until there's just
a single constructor to require and validate all attributes. From this point of view, we consider a web UI
databound component in Jenkins is nothing but a reusable component, and as such should never be used outside this
very specific context. Plugin developers who have reasons to expose a DataBound object as part of the public API
can define explicit public setters or annotate class as `@Restricted(None)`.

Based on this:

. databinding annotations can be used both on fields and accessors
. elements annotated databinding annotation will be automatically marked a restricted so they are not exposed as
"public API" whatever their Java visibility is.

==== Data Model API

Explicit metadata introduced in DataBound component should benefit various mechanisms relying on this, not
just web UI data binding. Typically structs-plugin and configuration-as-code-plugin replicate some of the
logic implemented by Stapler using reflection to introspect target components.

A global API to get a data model from a DataBound component with all available metadata has been considered,
but this discussion is now supperseded by [data-api effort](https://github.com/kohsuke/jep/tree/data-api/jep/0000/1)
driven by Antonio and Kohsuke.

== Backwards Compatibility

Annotation based databinding comes in addition to the legacy mechanisms supporter by stapler, so don't break
backward compatibility.

== Security

N/A

== Infrastructure Requirements

N/A
== Testing

N/A

== Prototype Implementation

https://github.com/stapler/stapler/pull/147

== References


* link:https://groups.google.com/d/topic/jenkinsci-dev/Bb4pIdpMMIY/discussion[Initial discussion]


