= JEP-12: Travel Grant Program
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 12

| Title
| Travel Grant Proposal Update

| Sponsor
| link:https://github.com/tracymiranda[Tracy Miranda]

| Status
| Draft :speech_balloon:

| Type
| Process

| Created
| 2018-08-24

| BDFL-Delegate
| link:https://github.com/rtyler[R. Tyler Croy]

|===

== Abstract

The Jenkins project provides travel grants to a limited number of community members to attend Jenkins related events.
This document describes the process by which travel grants may be requested and approved.

== Specification

=== Eligibility

All community members are eligible for travel grants.
However, as we have very limited funds to support this program, each community member may only receive one travel grant per year (based on the date of the event they plan to attend).
Grants are offered to individual community members, not companies. 

If you have other possible funding sources, please look to them first.
This will allow more people to attend Jenkins community events.

=== Grant Usage and Amounts

Funds received via this program may be used to cover any expenses related attending an event including but not limited to conference fees, hotel, and travel to and from the event.  
Grants will not exceed actual travel costs.

Regular travel grants are limited to 500 USD. 
Travel grants for more than 500 USD may be approved under 
link:#special-circumstances[special circumstances].

=== Application

To apply for a travel grant, send an email with the following information to the jenkinsci-dev mailing list at least two months before the event you want to attend.  

Requests for 500 USD or less only need to include basic information: 

* Your name
* The event you'd like to attend
* The expected cost of travel (airfare, hotel, conference fees, etc.)
* A short summary of recent contributions to the Jenkins project, such as:
** Plugins to which you contributed
** Pull requests you authored
** Documentation you wrote
** Public presentations made on Jenkins-related topics

==== Special Circumstances 

Requests for more than 500 USD should describe any special circumstances that justify the additional expenses, such as:

* Cost of city or distance travelled
* Number of days of the conference
* Additional merit of requester
* Whether you are a member of an underrepresented group in tech
* Any other mitigating circumstances

=== Review Process

All applications will be reviewed at a 
link:https://jenkins.io/project/governance/#meeting[Jenkins project governance meeting].
This meeting is usually held biweekly, see the 
link:https://jenkins.io/event-calendar/[Jenkins events calendar] 
for dates and times.

While applicants are free to attend the meeting in case there are any questions, they should refrain from active participation while their application is being discussed.

Each request will be discussed and recorded in the meeting minutes.
Applications by active contributors to the Jenkins project are more likely to approved.
Factors beyond the merits of the request itself may also be taken into consideration.  For example:

  * Whether budget for the year has been exceeded or underspent
  * Previous considerations for similar requests.

A vote will then be taken deciding whether to approve the travel grant request. 

Applicants will receive a response at least four weeks before the event.
This response will include the sponsored amount as well as to whom to send their receipts (see below).

=== Your Duties

If you are selected for a travel grant, you will be expected to be available for a blog post about this program before the event.

After the trip, please submit a travel report to jenkinsci-dev (same thread as your application).
This report should include the following:

* What you accomplished at the event
* What you learned at the event
* Contacts you made
* Other useful information

We also expect you to submit your receipts via email to the person mentioned in the travel grant confirmation for review.

== Motivation

The Jenkins project supports the development of a diverse and inclusive community.
One aspect of that community is Jenkins-related events. 
The Jenkins project has a certain amount of funding to support community developement, which it may use to help community members attend events.

== Reasoning

=== Amount 

The limit of 500 USD for regular grants was agreed to at the
link:http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-09-02-18.00.html[Governance meeting on 2015-09-02].
This is an arbitrary amount and it has been pointed out that it is low compared the total travel cost for many events.
This amount might change in the future. 

=== Allowing for Special Circumstances

At the Jenkins Governance meeting in August 2018 there was a travel grant request for more than USD$500.
A fixed amount does not always take into consideration other variables such as city of event as well as whether other submissions have been made in the year.

While many community members were in favour of granting additional funds it was agreed that a process definition should be in place for this, particularly to make it clear the what additional information is needed and who can apply.

This "special circumstances" allow for more flexibility with the goal of enabling as many of our community members as we can in participating.

== Backwards Compatibility

There are no backwards compatibility concerns related to this proposal.

== Security

There are no security requirements related to this proposal.

== Infrastructure Requirements

There are no infrastructure requirements related to this proposal.

== Testing

There are no testing issues related to this proposal.

== References

* link:https://groups.google.com/d/topic/jenkinsci-dev/FWq7zKeL6oU/discussion[jenkinsci-dev@ discussion]
* link:http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-09-02-18.00.html[Governance meeting discussion 2015-09-02]
* link:http://meetings.jenkins-ci.org/jenkins-meeting/2018/jenkins-meeting.2018-08-01-18.00.log.html[Governance meeting discussion 2018-08-01]
* link:https://wiki.jenkins.io/display/JENKINS/Travel+Grant+Program[Jenkins Travel Grant Program]


