= JEP-12: Travel Grant Proposal Update
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 12

| Title
| Travel Grant Proposal Update

| Sponsor
| link:https://github.com/tracymiranda[Tracy Miranda]

| Status
| Not Submitted :information_source:

| Type
| Process

| Created
| 2018-08-24

| BDFL-Delegate
| link:https://github.com/rtyler[R. Tyler Croy]

|===

== Abstract

====
This JEP provides an update to the existing Jenkins travel grant policy.

====

== Specification
The last line of the travel grant "We will reimburse actually incurred costs up to the 500 USD limit." is removed.
This is replaced with:
Typical travel grants approved are limited to 500 USD.
Travel grant requests for more than 500 USD will need to be requested through a Governance meeting.
Requests for 500 USD should provide mitigating circumstances which include:

  * Cost of city or distance travelled
  * Number of days of the conference
  * Additional merit of requester
  * Whether you are from a marginalized group in tech
  * Any other mitigating circumstances

The item will be discussed at a governance meeting and a vote will be taken, also taking into consideration other factors such as:

  * Whether budget for the year has been exceeded or underspent
  * Previous considerations for similar requests.

Travel grant requests made in this way will be recorded in the meeting minutes.

== Motivation
At the Jenkins Governance meeting in August 2018 there was a travel grant request for more than USD$500.
While many community members were in favour of additional funds it was agreed that a process definition should be in place for this, particularly to make it clear who may similarly apply.
This document aims to provide the process by which travel grants may be extended and who is eligible to apply.

== Reasoning
Jenkins community has a certain amount of funding to support community attending events.
A fixed amount does not always take into consideration other variables such as city of event as well as whether other submissions have been made in the year.
This process allows for some more flexibility with the goal of enabling as many of our community members as we can.

== Backwards Compatibility

There are no backwards compatibility concerns related to this proposal.

== Security

There are no security requirements related to this proposal.

== Infrastructure Requirements

There are no infrastructure requirements related to this proposal.

== Testing

There are no testing issues related to this proposal.


== References

* link:https://groups.google.com/d/msgid/jenkinsci-dev/20180801174530.GE3303%40grape.lasagna.io.[jenkinsci-dev@ discussion]
* link:http://meetings.jenkins-ci.org/jenkins-meeting/2018/jenkins-meeting.2018-08-01-18.00.log.html[Governance meeting discussion]
* link:https://wiki.jenkins.io/display/JENKINS/Travel+Grant+Program[Jenkins Travel Grant Program]


