= JEP-211: Java 11 support in Jenkins
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


.Metadata
[cols="2"]
|===
| JEP
| 211

| Title
| Java 11 support in Jenkins

| Sponsor
| link:https://github.com/oleg-nenashev[Oleg Nenashev]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Process

| Created
| 2018-07-05

| BDFL-Delegate
| link:https://github.com/oleg-nenashev[Oleg Nenashev]

| JIRA
|
link:https://issues.jenkins-ci.org/browse/JENKINS-52012[JENKINS-52012] - Preview in weekly releases,
link:https://issues.jenkins-ci.org/browse/JENKINS-51805[JENKINS-51805] - GA in weekly releases,
link:https://issues.jenkins-ci.org/browse/JENKINS-52284[JENKINS-52284] - GA in LTS,
link:https://issues.jenkins-ci.org/browse/JENKINS-40689[JENKINS-40689] - other non-blocker issues

| Discussions-To
| link:https://groups.google.com/forum/#!forum/jenkins-platform-sig[Jenkins Platform SIG]

//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| :bulb: JEP-NUMBER, JEP-NUMBER... :bulb:
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===

== Abstract

Java 11 was released on September 25, 2018.
It is an LTS version with a long support timeline.
This Jenkins Enhancement Proposal describes actions required
to make Jenkins releases for Java 11 publicly available in Weekly and LTS releases.

== Specification

The specification has been created according to the results of the link:https://jenkins.io/blog/2018/06/08/jenkins-java10-hackathon/[Jenkins and Java 10+ hackathon].

All stories in this JEP have tickets created in JIRA.
Stories are aggregated in
link:https://issues.jenkins-ci.org/browse/JENKINS-40689[JENKINS-40689],
link:https://issues.jenkins-ci.org/browse/JENKINS-52012[JENKINS-52012] and
link:https://issues.jenkins-ci.org/browse/JENKINS-52284[JENKINS-52284].

If the tickets are not linked in the description, they can be found there.
JENKINS-52012 and JENKINS-52284 EPICs are considered as mandatory in this JEP,
JENKINS-40689 - nice to have.

=== Goals and non-goals

Goals:

* Jenkins WAR packages run on Java 8 and Java 11
** Running on Java 11 *may* require extra options, e.g. for loading detached modules.
Although we have a plan for some cases (java.xml.bind for JAXB), there may be other modules requiring updates
* Jenkins on Java 11 is fully supported
* No big bang
** The most of core and plugin patches will be delivered in Weekly releases ahead of the Java 11 general availability announcements
** We will be landing these patches using the existing code review process and test automation flows

Non-goals:

* Jenkins is fully clean from “Illegal Reflective Access” warnings
** There are many known places where Jenkins prints warnings about Illegal reflective access
(see link:https://issues.jenkins-ci.org/browse/JENKINS-40689[JENKINS-40689])
** We acknowledge the problem, but we do not consider it as a blocker for Java 11 support.
By default OpenJDK 11 just prints a warning once on the startup, there is no short-term plan to change this behavior in OpenJDK
* All plugins are operational with Java 11
* Building all components with OpenJDK 11
** Some Jenkins components may be updated to support features offered in Java 9+, but there is no plan to update all tools
* Full multi-release JARs support in Development tools
* Cleanup of removed/deprecated features
** During Jenkins & Java 10+ Hackathon we have discovered several stories, which may impact Jenkins behavior on future versions:
*** Signal API is deprecated (JENKINS-51995)
*** Java Web Start is removed from Java 10+ (JENKINS-50301)
* There is no plan to remove all functionality as a part of this JEP, but it may be done and included into the release

=== Scope of changes

* Jenkins Core
* Docker Packaging for Debian
* Plugins
* Jenkins website: jenkins.io
* Jenkins CI instances:
    link:https://jenkins.io/projects/infrastructure/#jenkins[ci.jenkins.io],
    trusted-ci.jenkins.io,
    link:https://jenkins.io/security/#team[Security team]'s instance
* Maven Build flow (
    link:https://github.com/jenkinsci/maven-hpi-plugin[Maven HPI Plugin],
    link:https://github.com/jenkinsci/plugin-pom[Plugin POM],
    link:https://github.com/jenkinsci/pom[Jenkins POM],
    etc.)
* Test tools:
    link:https://github.com/jenkinsci/jenkins-test-harness[Jenkins Test Harness],
    link:https://github.com/jenkinsci/acceptance-test-harness[Acceptance Test Harness],
    link:https://github.com/jenkinsci/plugin-compat-tester[Plugin Compatibility Tester]
* User and Developer Documentation

Out of the scope for this JEP:

* Packaging in subprojects: Jenkins X, Jenkins Evergreen, Jenkinsfile Runner, etc.
  They will be handled in follow-up JEPs if needed.
* Gradle build flow, as well as other
* Windows Installers
  Their rework and Java removal is a separate project in Platform SIG.
* Docker packaging for Alpine/Slim
  See the reasoning below

=== Jenkins core patches

Must-have stories are defined in link:https://issues.jenkins-ci.org/browse/JENKINS-52012[JENKINS-52012].
All stories in this epic need to be completed.

==== Library updates

* The JENKINS-52012 epic includes a number of library updates in the core we know about: Groovy, ASM, etc.
* Some updates may require downstream plugin updates.
** For Example, Groovy update requires cleanup of the Metaspace leak memory in Script Security and Pipeline plugins

==== Core patches

* Jenkins JNLPLauncher built-in documentation will be updated to indicate that Java Web Start feature is not available in Java 10+
* https://github.com/jenkinsci/docker/tree/java11 is merged into master and deleted
* Extras Executable WAR patch to permit running with Java 11 is permitted without the “--enable-future-java” flag (JENKINS-52285)

==== Build flow updates (JENKINS-51903)

* Jenkinsfile is updated to run tests with JDK 11
** It includes Unit tests, JTH and ATH smoke tests
* It is possible to build Jenkins Core with the release profile on JDK 8

==== Plan for other Java 11 patches

There is a number of pending patches and tickets (e.g. detaching of JNA/JNR API, Lib Process Utils Patch, etc.),
which cleanup Illegal Reflective Access attempts in Jenkins.

* These patches will be reviewed and integrated into weekly releases once ready
* These patches do not block the Java 11 GA release

The patches will be tracked in the
link:https://issues.jenkins-ci.org/browse/JENKINS-40689[JENKINS-40689] EPIC.

=== Jenkins Docker packaging

==== Jenkins Master Images (JENKINS-51985)

* Official jenkins/jenkins image is available for Java 11. Suggested labels:
** jdk11
** lts-jdk11
** `VERSION`-jdk11
** …
* Automatic build flow on Trusted CI is updated to build and release images. Weekly and LTS releases are performed automatically
* https://github.com/jenkinsci/docker/tree/java11 experimental branch is integrated into the master branch and deleted to avoid confusion.

==== Jenkins Agent Images (JENKINS-52279, JENKINS-51986)

* https://github.com/jenkinsci/docker-slave, https://github.com/jenkinsci/docker-ssh-slave and https://github.com/jenkinsci/docker-jnlp-slave are updated to offer JDK 10 builds
** Version format is to be determined by the image maintainers
* DockerHub configurations are updated to automatically build images

==== BlueOcean Docker Image (JENKINS-52280)

* BlueOcean build for Java 11 should be made a part of the build/release flow for the component
* It can be done after the GA release

=== Plugins

link:https://issues.jenkins-ci.org/browse/JENKINS-52012[JENKINS-52012] tracks updates required in plugins.
There are the following conditions for the GA release:

* All plugins pass ATH with JDK 11
* All known issues are documented in the Java 11 Compatibility Issues Wiki page (see below)
* Plugin updates are mentioned in upgrade guidelines

Currently we know about 2 plugins which will need to be updated: “Pipeline: Support” plugin (JENKINS-52187), Monitoring Plugin (JENKINS-52092).
More plugin compatibility issues may be discovered during testing.

=== New policy: Building Jenkins components/plugins with JDK 11

The following policy is suggested:

* All Jenkins core components are required to retain compatibility with Java 8
  so that Jenkins can run with it
* All Jenkins plugins are required to retain Java 8 compatibility in GA releases
  without `alpha`/`beta` prefix
** Plugins may require Java 11 for `alpha`/`beta` releases **only**,
   and these versions can be made accessible in the experimental update center for Java 11
   (link:https://issues.jenkins-ci.org/browse/INFRA-1870[INFRA-1870])
** In order to support Java11-only `alpha`/`beta` releases,
   the plugins must use Plugin POM with link:https://issues.jenkins-ci.org/browse/JENKINS-20679[JENKINS-20679] patches
   (3.29 on Dec 06, 2018)
** The policy may be reconsidered once link:https://issues.jenkins-ci.org/browse/JENKINS-55048[JENKINS-55048] is integrated
   and widely adopted in Jenkins LTS
* Individual Jenkins components may choose to require JDK 11 to *build*
** It includes Jenkins core libs, plugins and potentially the core itself
** It is up to maintainers to decide when they are ready to accept such requirement in components they maintain
** Components that choose to require JDK 11 for building must have Jenkinsfiles running tests on Java 8 and Java 11
* Be explicit that all Java 11 support is available in the experimental mode until Jenkins officially supports it
(currently we consider Java 11 support as a preview mode - docs)
* If a downstream component includes Java 9+ bits (e.g. lib-process-utils),
downstream components (e.g. Jenkins core for lib-process-utils) must be still buildable and testable with JDK8

This policy may require patches in parent POMs:

* 2 Parent POMs should be updated: Jenkins POM and Plugin POM
* For known issues Maven plugin versions should be updated to versions compatible with JDK10+. Support of JDK 8 is a must (see “Building with JDK 11”)
* If builds on Java 11 work correctly after the patches, support for JDK 11 can be released for tools
* link:https://issues.jenkins-ci.org/browse/JENKINS-20679[JENKINS-20679] - Plugin POM should be updated to support `Minimum-Java-Version` metadata injection

=== Rollout plan

The rollout procedure should be coordinated within the link:https://jenkins.io/sigs/platform/[Platform SIG].

==== Timeline

* Experimental Java 11 Support is available in Jenkins 2.127+
** Announced in link:https://jenkins.io/blog/2018/06/17/running-jenkins-with-java10-11/[this blogpost]
** We have started integrating some patches starting from 2.127 when the “--enable-future-java” flag was introduced
** There is no official preview announcement for weekly releases at this stage
* link:https://issues.jenkins-ci.org/browse/JENKINS-52012[JENKINS-52012] - Preview in weekly releases
* link:https://issues.jenkins-ci.org/browse/JENKINS-51805[JENKINS-51805] - GA in weekly releases
* link:https://issues.jenkins-ci.org/browse/JENKINS-52284[JENKINS-52284] - GA in LTS
** Java 11 support will be available in LTS once the LTS baseline updates to the Weekly release
** No special timeline set, optimistic ETA is February 2018
* link:https://issues.jenkins-ci.org/browse/JENKINS-40689[JENKINS-40689] - other non-blocker issues

The referenced EPICs contain the detailed plan for what is included into the each milestone.

==== Website

* link:https://jenkins.io/doc/administration/requirements/java/[Java Support Page] is updated to indicate that Java 11 is supported
* link:https://jenkins.io/blog/2018/06/17/running-jenkins-with-java10-11/[“Running Jenkins with Java 10 and 11”] blogpost is updated to refer the new guidelines
* For Java 11 the website should be updated only after the official release of OpenJDK 11
* There is an announcement blogpost for Java 11 support general availability in weekly
** The blogpost will include upgrade guidelines, “make a backup” will one of the required steps there
* There is an announcement blogpost for Java 11 support general availability in LTS

==== Wiki

* There is a Wiki page created to track known Java 11 incompatibilities in the Jenkins Core and Plugins:
** https://wiki.jenkins.io/display/JENKINS/Known+Java+11+Compatibility+issues
** The page will have format similar to link:https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+fix+for+JEP-200[Plugins affected by fix for JEP-200] Wiki
* There is a Wiki page (or jenkins.io page) with developer guidelines explaining how to test plugins
  with Java 11 and how to resolve common issues
** https://jenkins.io/redirect/java11-developer-guidelines

==== Post-release support

After the release of Java 11 support, there may be a number of defects reported by early adopters.
It may cause additional workload on plugin and core maintainers who will need assistance with triage of issues after the release.

After the weekly release availability the _Java 11 Support Team_
(link:https://github.com/orgs/jenkinsci/teams/java11-support[@jenkinsci/java11-support])
will be responsible to provide an extra support for the issues:

* _Java 11 Support Team_ will periodically review open defects and triage them (e.g. once per week)
* _Java 11 Support Team_ may request additional information from the reporter. Finally, they are expected to communicate the triage outcome.
* Possible triage outcomes:
** Accepted by _Java 11 Support Team_. In such case one of maintainers assigns the issue to himself and delivers the fix
** Rejected by _Java 11 Support Team_ - functional defect in the plugin (e.g. reliance on Java version or private fields in Reflections) or lack of justification for a fix
** Issue is closed - Not a defect, Duplicate, etc.
* For accepted issues maintainers will prioritize and schedule the fix
** Java 11 support is considered as a “Feature” with an obvious workaround: “Downgrade to Java 8”
** Fixes for Java 11 will be prioritized by the team, but incompatibilities won’t be considered as Blocker issues if downgrade is possible
* Issues rejected by Java 11 maintainers will be assigned to component leads in JIRA (if any).

The proposed support model will be in place until “Availability in LTS + 2 months”.
After this period Jenkins component maintainers will be responsible for triaging and fixing issues in their components.
SECURITY reports will be triaged by the Jenkins Security Team.

_Java 11 Support Team_ is responsible to report the project status
at link:https://jenkins.io/sigs/platform/[Platform SIG] meetings and, if needed,
at Jenkins Governance meetings.

==== LTS Backporting

All backporting will be done according to the link:https://jenkins.io/download/lts/#backporting-process[LTS Backporting Process].

There is no plan to backport changes required for Java 11 support to previous LTS baselines.
Particular compatibility fixes may be backported on-demand,
but major updates will not be considered due to the serious risk of regressions.

== Motivation

In September 2018 we expect Java 11 to be released.
It is an LTS version with a long support timeline.
Over last year the Jenkins project has received many issue reports about Java 9 and then Java 10 compatibility.

* During Jenkins World 2017 hackfest Mark Waite and Baptiste Mathus invested
some time to explore Jenkins compatibility with Java 9
* In link:https://jenkins.io/changelog/#v2.111[Jenkins 2.111] we had to
prevent Jenkins from starting up on unsupported Java versions toprevent false expectations from users.
* In link:https://jenkins.io/changelog/#v2.127[Jenkins 2.127] we partially re-enabled
the behavior by offering a new `--enable-future-java` which allowed running with Java 9 and above
* Before the link:https://jenkins.io/blog/2018/06/08/jenkins-java10-hackathon/[Jenkins & Java 10+ Hackathon]
we offered preview versions of Jenkins on Java 10 and 11
(link:https://jenkins.io/blog/2018/06/17/running-jenkins-with-java10-11/[run guidelines])
* During the hackathon we were able to get major Jenkins features running
with Java 10 and 11.
See the summary link:https://docs.google.com/presentation/d/1hWWa6mYv86Kn8Ulu7uGlRJ9h2XTHlvHolO9CeRnnvcI/edit#slide=id.g1a6800f862_0_0[here]
* We made progress with regards to Java 11 during the DevOps World | Jenkins World 2018 hackathon,
  key issues like Pipeline metaspace leaks are addressed

Taking the success of the Jenkins and Java 10+ hackathon,
there is an interest to continue working on these stories towards making
Java 11 support available in Jenkins releases (weekly and then LTS).

== Reasoning

“Goals and non-goals” section in the specification lists design decisions taken
to ensure it can be delivered by a small team.
Non-goals in the specification are defined to limit the scope of work.
The main objective is to get Jenkins running with Java 11,
there will be follow-up tasks to cleanup Illegal Reflective Access warnings and to adopt new features.

=== Support of Java 10 and 12

Originally this JEP was targeting support of Java 10 and Java 11 early access.
Java 10 is in the End of Life starting from 25.09.2018 when Java 11 was officially released.
To limit the scope, Java 10 support was excluded from this JEP.
We will not be testing new patches with Java 10 and providing Docker packages with this version.
It may be possible to run Jenkins WAR files with Java 10 as it is described link:https://jenkins.io/blog/2018/06/17/running-jenkins-with-java10-11/[here],
but _Java 11 Support Team_ will not provide support for Java 10 issue reports
unless the issues are reproducible on Java 11.

Java 12 is in the early access state at the time this JEP is accepted (Dec 12, 2018).
Although we are interested to invest into adopting new Java versions,
it is also out of the scope of this JEP.
We will not be testing new patches with Java 12 and providing Docker packages with this version.
Issue reports from early adopters may be triaged,
but Java 12 won't be officially supported as a part of this JEP.

=== Docker packaging for Alpine/Slim

Jenkins offers official slim and Alpine packages for Java 11.
These images are based on the standard link:https://github.com/jenkinsci/docker[jenkins/docker] image.
Unfortunately there is no packaging provided for Alpine now.
Hence there is a decision to not add Alpine images to the scope of this JEP.

Current JEP does NOT consider migrating to another base image.
There is a well-known issue with OpenJDK distributions by Oracle,
but it is not clear how it is going to impact the Docker images we use.
The provider may just start building Java on its own.

Postponing of Alpine/Slim packaging also postpones the question of multi-classifier images (like `alpine-jdk11`).

=== Docker image labeling for JDK8

As a part of this JEP, we do not change labeling for JDK8.
These images will be posted as is without explicit reference to Java version in these images (`latest`, `lts`, `slim`, `alpine`).
Changing of the image label may be reconsidered once there is a JEP proposed for changing default labels to Java 11 or another base image.
It is not in the scope for this JEP.

=== Experimental Update Center for Java 11

During the preview availability preparation it was discovered that the
link:https://plugins.jenkins.io/workflow-support[Pipeline: Support Plugin] compatibility fix (link:https://issues.jenkins-ci.org/browse/JENKINS-51998[JENKINS-51998])
is being delayed due to the discovered compatibility-breaking changes.
We discussed an option to ship and `alpha`/`beta` release to the
link:https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/[Experimental Update Center],
but this option would cause additional risk for Java 8 users who use this update center.

It was decided to create a new **temporary** update center so that custom
Java 11 patches can be quickly deployed and used by Java 11 adopters.
It will complement the timestamped snapshots and Incremental releases link:/jep/305[JEP-305] which can be used by developers.

In order to deliver the patches,
the Maven HPI Plugin should inject `Minimum-Java-Version` manifest entry
which will be later processed by the Update Center generator.
There is a link:https://issues.jenkins-ci.org/browse/JENKINS-20679[JENKINS-20679] for it and
some patches proposed by Daniel Beck.

The update center deployment is tracked as link:https://issues.jenkins-ci.org/browse/INFRA-1870[INFRA-1870],
see the specification below.

== Backwards Compatibility

The following backward compatibility requirements are defined:

* Jenkins Core and Updated plugins should fully support JDK 8
* In the case of compatibility issues, it is possible to migrate from Java 11 to Java 8 by replacing Java in PATH or by replacing the official Docker image
** Java 8 and Java 11 XML formats are similar

== Security

=== Process

Only Java 11 with the latest security fixes will be supported at the moment of the public release.

Starting from the Java 11 preview availability,
we adopt a partial security process for Java 11 issues.
Approach:

* Security issues for Java 11 should be always reported according
  to the link:https://jenkins.io/security/#reporting-vulnerabilities[standard vulnerability reporting process].
  It is mandatory, because it is required potential impact on Java 8 users
* Security issues for Java 11 will be triaged by the _Java 11 Support Team_,
  the team should include Security team members
* Security fixes for Java 11 Preview that do *not* apply to instances with a Java 8 runtime, may be delivered directly to the Core and Plugins in public,
  the releases will not be coordinated by the Jenkins Security Team in such case
** Conversely, this means that any security issue targetting both Java 11 *and* Java 8 will obviously be processed in private and as usual by the Jenkins Security Team
* Security advisories will not be published unless deemed necessary
  by the _Java 11 Support Team_ and the Jenkins Security Officer

Starting from the Java 11 general availability,
Jenkins security issues on Java 11 will be processed according to the
standard link:https://jenkins.io/security/[Jenkins Security Process].


=== Security risks

* In particular cases Java 11 may introduce new security defects
  (e.g. Groovy Sandbox escaping in Script Security plugin)
** As a part of the Preview availability,
   we acknowledge the potential risk of security regressions when running Jenkins with Java 11.
   Preview versions of Java 11 are supposed to be used for evaluation only
** In order to mitigate the Groovy update risk, Groovy will not be updated to 3.x in the incoming GA release.
It means that Java 9+-alike features will not be available in Groovy DSLs within Jenkins
** If a security issue is reported, is will be reviewed with a high priority by the _Java 11 Support Team_

== Infrastructure Requirements

=== ci.jenkins.io

* Tool Infrastructure should offer the latest version of OpenJDK 11 - link:https://issues.jenkins-ci.org/browse/INFRA-1688[INFRA-1688]
* OpenJDK 11 should be added to `ci.jenkins.io` (`jdk11`)

=== Jenkins Pipeline Library

* `buildPlugin()`, `runATH()`, and `runPCT()` should support running tests with JDK 11 (
link:https://issues.jenkins-ci.org/browse/INFRA-1690[INFRA-1690],
link:https://issues.jenkins-ci.org/browse/INFRA-1691[INFRA-1691],
link:https://issues.jenkins-ci.org/browse/INFRA-1692[INFRA-1692])
* It is possible to do fine-grain configurations in `buildPlugin()`,
so we do not run Java 11 tests on core versions which do not support it
(link:https://issues.jenkins-ci.org/browse/INFRA-1687[INFRA-1687])
* essentialsTest() should support defining Java version matrix for testing
(link:https://issues.jenkins-ci.org/browse/INFRA-1693[INFRA-1693])

=== DockerHub

* CD Flow for JDK 11 images is updated to support the Master branch with Java 11 packages
(link:https://issues.jenkins-ci.org/browse/INFRA-1694[INFRA-1694])
* If necessary, DockerHub configuration should be adjusted to host official
  master and agent images for Java 11

=== Temporary Experimental Update Center for Java 11

* A new temporary update center should be deployed
(link:https://issues.jenkins-ci.org/browse/INFRA-1870[INFRA-1870])
* The patches must not impact output of the `latest` and `stable` update centers
* The patch must ensure that Java11-only updates do not get to the standard
  link:https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/[Experimental Update Center]
* Name of the update center: `temporary-experimental-java11`
* This update center will stay available until May 2019 at least.
  After that the Jenkins infrastructure team may remove it after coordinating the change
  with the _Java 11 Support Team_

== Testing

Java 11 support in Jenkins requires a serious amount of testing.
During link:https://jenkins.io/blog/2018/06/08/jenkins-java10-hackathon/[Jenkins and Java 10+ hackathon] there was a significant amount of exploratory testing performed,
and after several patches there was no major issues discovered.
More tests should be performed.

In order to track the testing effort, a status Google doc has been created:
link:https://docs.google.com/document/d/1oluVrNVpQhXCIwW9CYVm09Y1vPc3H77d3q92LrzcpDw/edit[here].
Testers are welcome to report their results there.

Tests to be performed:

* ATH is performed on Java 11
(link:https://issues.jenkins-ci.org/browse/JENKINS-52309[JENKINS-52309])
* BlueOcean ATH is performed with Java 11
(link:https://issues.jenkins-ci.org/browse/JENKINS-52310[JENKINS-52310])
* PCT is performed on Java 11, at least for the recommended plugins
(link:https://issues.jenkins-ci.org/browse/JENKINS-52312[JENKINS-52312])

In order to perform such testing,
ATH and PCT tools should be updated to support Java 11.

== Prototype Implementation

Prototype implementation has been created during Jenkins & Java 10+ hackathon. There is no plans to create additional prototypes.
These prototypes include Jenkins core, Docker updates and downstream demo patches.

* https://github.com/jenkinsci/jenkins/tree/java11-support
* https://github.com/jenkinsci/docker/tree/java11
* https://github.com/jenkinsci/blueocean-plugin/blob/master/Dockerfile.jdk10
* https://github.com/oleg-nenashev/demo-jenkins-config-as-code/pull/6
* https://github.com/gmacario/easy-jenkins/pull/270
* https://github.com/oleg-nenashev/jenkins-blueocean-experimental/tree/java11
* https://hub.docker.com/r/jenkins4eval/blueocean-platform-support/

== References

* link:https://jdk.java.net/11/release-notes[JDK 11 Release notes]
* link:http://www.oracle.com/technetwork/java/javase/eol-135779.html[Oracle Java SE Support Roadmap]
* link:https://jenkins.io/doc/administration/requirements/java/[Java requirements] in Jenkins
* link:https://jenkins.io/blog/2018/06/08/jenkins-java10-hackathon/[Jenkins & Java 10+ Hackathon]
* link:https://jenkins.io/doc/administration/requirements/java/#running-jenkins[Running Jenkins with Java 10 and 11]
* link:https://docs.google.com/document/d/1oluVrNVpQhXCIwW9CYVm09Y1vPc3H77d3q92LrzcpDw/edit#[Java 11 Testing status document]
* link:https://github.com/orgs/jenkinsci/teams/java11-support[Jenkins Java 11 Support Team]
* link:https://wiki.jenkins.io/display/JENKINS/Known+Java+11+Compatibility+issues[Known Java 11 Compatibility issues wiki page]
* link:https://jenkins.io/redirect/java11-developer-guidelines[Developer Guidelines]
