#!/usr/bin/env bash

cat > README.adoc <<EOF
= Index of Jenkins Enhancement Proposals

[%header, cols="^1,<.^4,^1,^1"]
|===
.^| Status
.^| Title
.^| Sponsor
.^| BDFL Delegate

EOF

for f in $(ls | sort -n); do
    if [ -f "$f/README.adoc" ]; then
        echo "> Processing JEP-$f";
        description=$(head -n 1 $f/README.adoc | sed 's/^=\ //')
        # grep -A doesn't work on osx grep, use sed instead
        #jep_status=$(grep -x -m 1 -A 1 -e "| Status" $f/README.adoc | tail -n 1)
        jep_status=$(sed -n '/| Status/,/|/p' $f/README.adoc | head -n 2 | tail -n 1 | sed 's/\ :/{nbsp}:/')

        if [ $? -ne 0 ]; then
            jep_status="Unknown"
        fi;

        sponsor=$(sed -n '/| Sponsor/,/|/p' $f/README.adoc | head -n 2 | tail -n 1 | sed 's/\([a-zA-Z.]\) /\1{nbsp}/g')
        #sed 's/\(\[[^\]]+\) \([^\]]+\]\)/\1{nbsp\}\2/')


        bdfl=$(sed -n '/| BDFL-Delegate/,/|/p' $f/README.adoc | head -n 2 | tail -n 1 | sed 's/\([a-zA-Z.]\) /\1{nbsp}/g' | grep -ve "^//" )
        if [ $? -ne 0 ]; then
            bdfl="| _not{nbsp}delegated_"
        fi;

        cat >> README.adoc <<EOF
$jep_status
| link:${f}/[$description]
$sponsor
$bdfl

EOF

    fi;
done;

echo "|===" >> README.adoc
