#!/usr/bin/env bash

cat > README.adoc <<EOF
= Index of Jenkins Enhancement Proposals

[cols="^,>,^"]
|===
| Status | Title | BDFL Delegate

EOF

for f in $(ls | sort -n); do
    if [ -f "$f/README.adoc" ]; then
        echo "> Processing JEP-$f";
        description=$(head -n 1 $f/README.adoc | sed 's/^=\ //')
        # grep -A doesn't work on osx grep, use sed instead
        #jep_status=$(grep -x -m 1 -A 1 -e "| Status" $f/README.adoc | tail -n 1)
        jep_status=$(sed -n '/| Status/,/|/p' $f/README.adoc | head -n 2 | tail -n 1)

        if [ $? -ne 0 ]; then
            jep_status="Unknown"
        fi;

        bdfl=$(sed -n '/| BDFL-Delegate/,/|/p' $f/README.adoc | head -n 2 | tail -n 1 | grep -ve "^//")
        if [ $? -ne 0 ]; then
            bdfl="| _not specified_"
        fi;

        cat >> README.adoc <<EOF
$jep_status
| link:${f}/[$description]
$bdfl

EOF

    fi;
done;

echo "|===" >> README.adoc
