ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Jenkins Enhancement Proposals

JEP stands for Jenkins Enhancement Proposal.
A JEP is a design document that
describes a new feature or aspect of Jenkins itself, or Jenkins project, plugin, processes or environment.
A JEP provides a concise technical specification of the feature,
describes the motivation for the change,
and discusses the rationale behind the design.

JEPs are the primary mechanism for proposing major new
features, for collecting community input on an issue, and for
documenting the design decisions that have gone into Jenkins.

* See link:jep/1/README.adoc[JEP-1] for a description of JEPs and the JEP process.
* link:https://github.com/jenkinsci/jep/blob/master/jep/README.adoc[Index of all JEPs] approved at least as drafts.

== License

This repository's contents are considered under the
**link:https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0] license**.

You are free to:

* **Share** - copy and redistribute the material in any medium or format
* **Adapt** - remix, transform, and build upon the material for any purpose, even commercially.

Under the following terms:

* **Attribution** - You must give appropriate credit, provide a link to the
  license, and indicate if changes were made. You may do so in any reasonable
  manner, but not in any way that suggests the licensor endorses you or your
  use.
* **ShareAlike** - If you remix, transform, or build upon the material, you must
  distribute your contributions under the same license as the original.
