ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Jenkins Enhancement Proposals

See link:jep/1/README.adoc[JEP-1] for a description of JEPs.

link:jep/[Index of all JEPs] accepted at least as drafts.

== License

This repository's contents are considered under the
**link:https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0] license**.

You are free to:

* **Share** - copy and redistribute the material in any medium or format
* **Adapt** - remix, transform, and build upon the material for any purpose, even commercially.

Under the following terms:

* **Attribution** - You must give appropriate credit, provide a link to the
  license, and indicate if changes were made. You may do so in any reasonable
  manner, but not in any way that suggests the licensor endorses you or your
  use.
* **ShareAlike** - If you remix, transform, or build upon the material, you must
  distribute your contributions under the same license as the original.
