= JEP-304: Essentials Client Error Telemetry Logging
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


.Metadata
[cols="2"]
|===
| JEP
| 304

| Title
| Essentials Error Telemetry Logging

| Sponsor
| https://github.com/batmat

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Standards

| Created
| 2018-03-30
//
//
// Uncomment if there is an associated placeholder JIRA issue.
| JIRA
| link:https://issues.jenkins-ci.org/browse/JENKINS-49805[JENKINS-49805]
//
//
// Uncomment if there will be a BDFL delegate for this JEP.
| BDLF-Delegate
| https://github.com/rtyler[R. Tyler Croy]
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
| Requires
| link:https://github.com/jenkinsci/jep/tree/master/jep/300[JEP-300],
link:https://github.com/jenkinsci/jep/tree/master/jep/301[JEP-301]
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

Sending error logging to the backend is a critical aspect of Essentials to be able to implement the _Automated Health Assessment_ story
footnote:[a dedicated proposal will be written for this in link:https://issues.jenkins-ci.org/browse/JENKINS-50294[JENKINS-50294]].

_Jenkins Essentials_ needs a way to _extract_ the error logging from the Jenkins instance.

The current document describes how we plan to extract those logs so that the _evergreen-client_ can find, process and send them to the backend.

== Specification

Jenkins will be configured to send the logs to the _evergreen-client_.
The client being already link:https://github.com/jenkinsci/jep/tree/master/jep/303[connected] by definition, this will avoid having to maintain two ways to authenticate and access the backend.

=== Summary

Logs are sent:

* in `JSON` format for easier parsing by the client.
** Each log entry separated by a newline, so that each line can be parsed as a JSON object, without needing a JSON streaming parser.
* only if the level is greater or equal to _WARNING_.
* to the disk, under `$JENKINS_VAR/logs/essentials.log.N` rotating files.
** By rotating, we mean `essentials.log.0` is the one file to "tail" to receive new log entries.
It is left to the consumer to decide how to know where to start from in case of a fresh start, or restart.
Though it is a subject for another design document, it is suggested to:
*** store the last timestamp that was read ;
*** be able to idempotently send everything to the backend (in case of a fresh startup, or a missing value for the last read and sent timestamp), and that already sent logs are deduplicated or ignored there.
* in _UTF-8_ (The _JSON_ specification allows some other encodings. We restrict it to _UTF-8_ only)
** 5 files maximum ;
** Approximately 10 MB maximum per file.
** This should give largely enough time for the client to parse and send everything before it gets rotated, even more because only logs ≥ `WARNING` will be sent.
A total maximum of 50 MB of disk consumption for all this seems very reasonable with modern disk sizes.

=== Jenkins Plugin

We will host the code for all this in a new _Essentials Jenkins Plugin_ that will be required to be installed and active on any _Jenkins Essentials_ instance.

See <<plugin-or-module>> for why a Jenkins plugin.

=== Logging format

CAUTION: The JSON excerpts below are pretty-printed for readability.
This will **not** be the case in real conditions so that one line is one log entry.

The logs is sent in `JSON` format.
A version tag is put with initial value 1.
This will make it easier to evolve the format if needed.

The formatting is done by a `JSONFormatter` extending link:https://docs.oracle.com/javase/8/docs/api/java/util/logging/SimpleFormatter.html[`java.util.logging.Formatter`].

[source,json, title=Required fields for a single log entry]
{
  "version": 1,
  "timestamp": 1522840762769,
  "name": "io.jenkins.plugins.SomeTypicalClass",
  "level": "WARNING",
  "message": "the message\nand another line"
}

version:: Initially `1`.
Will be used in case we need to evolve the format.
timestamp:: Timestamp for the log in Epoch format
name:: The logger name.
It is generally the name of the emitting class, but can be any text or even the empty string.
level:: The level of criticality of the log.
In practice, should always be `SEVERE` or `WARNING`.
But it is expected that this could be any value of the `java.util.logging.Level` class, if this proves necessary in the future.
message:: The message for this log entry.
exception:: See below <<exception-handling>>.

[[exception-handling]]
==== Exceptions handling

Exceptions are serialized in a `exception` field.
This field can be absent.

==== Newlines and special characters

As `JSON` does not allow multiline strings, newlines are encoded using the typical `\n`.

=== Destination

The logs are written to disk in rotating log files under `$JENKINS_VAR/logs`.
This uses a custom `FileHandler`.

NOTE: This part is really meant to stay an internal implementation detail: the main goal is to have the client able to access and send those logs.
So we might in the future change that for instance to send those logs to the client directly using a local socket connection (see <<why-not-socket>>).

==== Rotation parameters

As explained previously, we plan to rotate on _5_ files, of _10 MB_ each maximum.
If contrary to what we think, this proves not enough, or too much, we will be able to easily adjust those settings by delivering a new version of the _Essentials Jenkins Plugin_ handling this.

== Motivation

There is no existing tooling for this.

== Reasoning

[[why-not-socket]]
=== Why not send logs to the client using a socket

The `SocketHandler` class provided by the JDK is not usable for any real life usage.
There is no reconnection logic at all: this means that *any* even temporary unavailability of the server socket will break the connection, and no logs will ever be sent again when it becomes available.

So we chose the easiest path to *not* roll our own `SocketHandler` at least for now, and use a `FileHandler` and rotating log files instead for more out-of-the-box robustness (the producer can send its data, and the consumer can read it when ready).

[[plugin-or-module]]
=== Packaging: Jenkins plugin or Jenkins module

We chose the Jenkins plugin path because this is a simpler path forward.
The _Jenkins Project_ has already everything ready to handle the hosting and release process of plugins.

Using a `jenkins-module` would mean we need to set up a custom Jenkins WAR build for Essentials.
This would also mean we cannot use the quality assurance improvements we have started to put in place in the same way for Essentials, and for the standard Jenkins core delivery.

Though having a dedicated WAR packaging for _Jenkins Essentials_ is very likely something we will do in the future, we deemed preferrable to defer it to later, and focus instead on the other yet unresolved design questions of Essentials.

=== The `exception` field in the JSON logs

Following link:https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it[YAGNI], we use a simple `exception` field where the exception is basically serialized as text.
We will likely use `hudson.Functions.printThrowable()`
footnote:[which formats chained exceptions more readably than `Exception.printStackTrace()`.]
for the text formatting.

If needed, this _might_ be replaced in the future by a richer structure.
In such case we will bump the `version` field to a higher number.

== Backwards Compatibility

=== `JSON` format versioning

As explained above, we put a `version` field in the JSON logs.
This will help accomodate a format change if this becomes a necessity.

=== Logs handling

We might decide at some point to change the way we pass the logs from _Jenkins_ to the Evergreen Client.
If this happens, we will probably go through a period of time where we'd log both to the disk, and to the Socket, so that we are not dependent on the version of the client.

== Security

There are no security risks related to this proposal.

NOTE: The sensitive part of this feature lies in sending data outside of the instance.
This will be handled in link:https://issues.jenkins-ci.org/browse/JENKINS-49811[JENKINS-49811].

== Infrastructure Requirements

There are no new infrastructure requirements related to this proposal.

The infrastructure side of this feature will be handled in link:https://issues.jenkins-ci.org/browse/JENKINS-49811[JENKINS-49811].

== Testing

=== JSON Logging as and where expected

The biggest part of this feature should be tested directly in the link:https://github.com/jenkins-infra/evergreen/[Evergreen] codebase.
It is indeed easy to check that the logs are indeed found under the expected location.
* See https://github.com/jenkins-infra/evergreen/pull/43 for such example

=== Test with the plugin

The _Essentials Jenkins Plugin_ is going to start introducing some core changes to the way Jenkins logs things.

We want to check we do not inadvertently change, or disable totally for instance, the usual logging Jenkins has.

== Prototype Implementation

* link:https://github.com/jenkins-infra/evergreen/[Jenkins Essentials official repository]
** More specifically: https://github.com/jenkins-infra/evergreen/pull/43
* https://github.com/batmat/essentials-plugin/ (will be moved to https://github.com/jenkinsci as soon as the feedback is gathered and the overall feedback validates this design)

== References

* link:https://issues.jenkins-ci.org/browse/JENKINS-49805[JENKINS-49805]
* Mailing list related threads:
** link:https://groups.google.com/d/msg/jenkinsci-dev/1qtL_ADxfFE/W2_1UOzJAAAJ[Thoughts on sending error telemetry for Jenkins Essentials]
** link:https://groups.google.com/d/msg/jenkinsci-dev/sS8XQbnm9cg/xXEOFx-GBwAJ[Where to store necessary classes: plugin or a core module?]
** link:https://groups.google.com/d/msg/jenkinsci-dev/IrNOfrlgEEw/MiR5wDiXAQAJ[Early draft review of this JEP]

[IMPORTANT]
====
When moving this JEP from a Draft to "Accepted" or "Final" state,
include links to the pull requests and mailing list discussions which were involved in the process.
====
