= JEP-237: FIPS-140 support
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 237

| Title
| FIPS-140 Support

| Sponsor
| link:https://github.com/jtnord[James Nord]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Standards

| Created
| 2023-09-06

| BDFL-Delegate
| TBD

//
//
// Uncomment if there is an associated placeholder JIRA issue.
// the following is just one Jira - there may be more so not spcifically linking
//| JIRA
//| https://issues.jenkins-ci.org/browse/JENKINS-71971[JENKINS-71971]
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| Link to where discussion and final status announcement will occur
//
//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| JEP-NUMBER, JEP-NUMBER...
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| JEP-NUMBER
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| Link to relevant post in the jenkinsci-dev@ mailing list archives

|===

== Abstract

This proposal makes it possible to run Jenkins in such a way that it would be link:https://csrc.nist.gov/pubs/fips/140-2/upd2/final[FIPS-140] compliant.  Not all features may be possible to use in this mode of operation, and plugins may need to change their behaviour at runtime.
Configuration of the JVM, platform etc. is out-of-scope, as is making every feature/plugin compliant.


== Specification

* A new API will be introduced that code can use to check if FIPS-140 compliance is preferred.
* Code in Jenkins core (where necessary) switches behaviour between more secure yet non compliant cryptography to FIPS-140 compliant cryptography.
* Non compliant and less secure crytpography has been replaced by a secure and compliant option.
* General guidelines exist to help developers write FIPS-140 compliant code and/or understand incompatibilities with the standard.
* User facing documentation provides a mere overview of the FIPS flag and what it does (and does not do).

== Motivation

Currently it is not possible to run Jenkins in a link:https://csrc.nist.gov/pubs/fips/140-2/upd2/final[FIPS-140-2] compliant way.  Many users needing Jenkins are required (e.g. for US government projects) to have any solution be compliant with FIPS-140 and today it is not possible for them to do this. 

Both Jenkins core and plugins use cryptography that is not allowed and/or are not from an approved implementation, and this prevents adoption of Jenkins by these end users.
Examples would be during setup where the install wizard creates a first admin user using the internal security realm which uses ``bcrypt`` which would fall foul of the standard due to its use of ``blowfish`` which is not an approved algorithm.

== Reasoning

To be FIPS-140 compliant, Jenkins must use validated, FIPS-140 compliant encryption algorithms. 
This requires complex configuration of the host, the Java Virtual Machine (JVM), the servlet environment, and the Jenkins controller. 
Changes may be required in both Jenkins core and plugins.
As such it is not considered that the Jenkins community supports or provides instructions on how to run Jenkins in a compliant manner, but merely states that FIPS-140 compliant operation may be  possible with appropriate configuration of the JVM, Servlet environment, limited set of plugins, and finally instructing Jenkins to prefer a FIPS-140 mode of operation.

As of the time of writing the validated Java implementations are only FIPS-140-2 compliant even though FIPS-140-3 has superseded it.  As such the initial implementations will be targeting the older FIPS-140-2 standard.

== Backwards Compatibility

It is out of scope to support previous configuration, as it would not be possible to migrate non FIPS-140 compliant data to FIPS-140 compliant data within a FIPS-140 compliant environment.  As such there is no backwards compatibility with previous versions.

It may but is not a requirement of this JEP be possible to switch from a FIPS-140 compliant environment to a non FIPS-140 compliant environment.

Code changes will however be backwards compatible; if the system is running in a non FIPS-140 compliant environment then it will continue to run and operate the same after any changes due to this JEP.

== Security

Some of the cryptography supported in FIPS 140 (especially FIPS 140-2) is considered less secure than some modern alternatives.  FIPS 140-2 cryptography will be used when Jenkins is running in FIPS-140 mode even if that cryptography is considered less secure than other alternatives.

== Infrastructure Requirements

There are no new infrastructure requirements related to this proposal.

== Testing

New code that changes behaviour when it detects the desire to run in FIPS-140 mode would be covered by unit tests like any other code change.  There would be no new testing introduced in a FIPS-140 compliant environment due to the complexity of maintaining this setup.

Test automation is not expected to detect code in Jenkins core or in Jenkins plugins that is not FIPS-140 compliant.

== Prototype Implementation

link:https://github.com/jenkinsci/jenkins/pull/8393[Jenkins#8393] contains a prototype for enabling a FIPS-140 preference flag that code can adapt behaviour to, as well as a change in behaviour for the ``HudsonPrivateSecurityRealm``.


== References

* link:https://csrc.nist.gov/pubs/fips/140-2/upd2/final[FIPS-140-2]
* link:https://csrc.nist.gov/pubs/fips/140-3/final[FIPS-140-3]

