= JEP-8: Google Summer of Code Budgeting and Expenses
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


.Metadata
[cols="2"]
|===
| JEP
| 8

| Title
| Google Summer of Code Budgeting and Expenses

| Sponsor
| link:https://github.com/oleg-nenashev[Oleg Nenashev]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Process

| Created
| 2018-07-17

//| BDFL-Delegate
//| :bulb: Link to github user page :bulb:
//
//
//
// Uncomment if there is an associated placeholder JIRA issue.
//| JIRA
//| :bulb: https://issues.jenkins-ci.org/browse/JENKINS-nnnnn[JENKINS-nnnnn] :bulb:
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| :bulb: JEP-NUMBER, JEP-NUMBER... :bulb:
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===

== Abstract

This document documents the Google Summer of Code (GSoC) budgeting process.

== Specification

=== Budget sources

The budget sources are:

* Payments by Google according to the
link:https://developers.google.com/open-source/gsoc/help/org-payments[Payments to Google Summer of Code Organizations ]
* Other donations to the Jenkins project,
which explicitly target GSoC

All payments are transferred to the Jenkins account
provided by the link:https://www.spi-inc.org/[Software In Public Interest] non-profit organization,
or to other official Jenkins treasury account.

=== Using the budget

The Google Summer of Code budget can be used ONLY to promote Google Summer of Code in the Jenkins project
or to fund the ongoing Google Summer of Code
or Google Code-In projects.
It should not be used for other purposes,
unless confirmed with GSoC organization admins.

Possible usages:

1. Travel grants for GSoC students in order to participate in Jenkins community or industry events
** Examples: Jenkins Area Meetups, Jenkins World,
open-source conferences like FOSDEM, etc.
** Travel grants may cover: hotel, transportation costs, visa fees, travel insurance, meals
** Transportation costs may be covered only for economy-class travel
** Travel grants do NOT cover: conference fees, alcohol, souvenirs, etc.
2. GSoC Mentor Summit travel grants for GSoC mentors and org admins
** The budget is provided according to the rules defined in link:https://developers.google.com/open-source/gsoc/help/org-payments[GSoC Org Payments] (as of 2018 - 2200 USD)
** Mentor travel grants may cover: transportation costs, visa fees, meals
** Transportation costs may be covered only for economy-class travel
** Travel grants do NOT cover travel expenses to any other events
** Travel grants do NOT cover expenses that are already covered event organizers, or other types of sponsors.
3. Project expenses for students
** GSoC budget may be used to cover particular expenses for projects: special equipment costs, SaaS hosting
** Project expenses should happen within the GSoC timeframe between start of Community Bonding and end of the last coding phase
** GSoC budget may not be used to cover generic equipment costs: laptop, IDEs, internet, etc.
** GSoC budget may not be used to cover software license costs.
The most of the projects are expected to be doable with only open-source or freeware software,
otherwise it is up to the students and mentors to get the setup.
** Total project expenses may not exceed the amount being payed by Google per project (as of 2018 - 500 USD)
4. Promotional materials
** GSoC budget may be used to promote Google Summer of Code by distributing swag, e.g. stickers, T-shirts and other items.
Swag may be sent to participants or distributed at community events.
** GSoC budget may be used to cover swag production costs and delivery costs by regular mail
** Swag may be sent out to active GSoC participants, including GSoC students, mentors, org admins, applicants, and other contributors who participated in GSoC
** GSoC budget may not be used for any kind of payed advertisement or
payments to external individuals/organizations for promotion.
** GSoC budget may not be used to send out promotional materials which explicitly or implicitly reference other trademarks or commercial companies

=== Approval process

* All expenses should be pre-approved with
Jenkins GSoC org admins before the expenses are incurred, and as a pre-condition for payment
* Jenkins org admins are eligible to approve the requests only within the GSoC budget defined in this JEP
* All payments beyond this budget should be approved by Jenkins Governance Meeting or Jenkins Board
* According to the SPI process,
the GSoC-related expense reports still need approval by Jenkins Board
once submitted (see _Payment process_)

=== Payment process

* Jenkins project does not pay for expenses,
but it reimburses expenses post-factum to students, mentors or Org Admins
* Reimbursements are performed according to the SPI process defined
link:https://wiki.jenkins.io/display/JENKINS/Reimbursement+of+Expenses+via+SPI[Reimbursement of Expenses via SPI]
* It may take a while to get an expense report reimbursed
(see the _Liability_ section)
* It is **recommended** that GSoC mentors do the payments for students
and then seek reimbursement for the expenses. Pre-approval is still required in this case.

=== Liability

Jenkins project has no legal entity which can commit
on expenses.

This means:

* Approval by GSoC org admins does not guarantee the payments
* Jenkins project, GSoC org admins or SPI cannot guarantee ETA of any payment or, in the worst case,
the payment itself
* Jenkins Project or SPI cannot issue guarantee letters for
visa applications or other or other travel documents.

=== Unused budget from previous years

Unused budget from previous years are transferred to the next year.
Unused budgets for GSoC mentor summit travel grants may be used for different purpose once transferred
to the next year.

=== Transparency

* GSoC Org Admins report to the Jenkins Governance Board regarding the budgeting
* GSoC Org Admins are responsible to report the current budget status at the
Jenkins Governance meeting at least twice per year:
** As a part of GSoC preparation process (est. January or February)
** After all GSoC payments are done (est. October)
* GSoC Org Admins are responsible to report on the budget at the
Jenkins Governance Meeting upon request

== Motivation

Jenkins operates in Google Summer of Code within rules defined by Google,
and it gets dedicated payments.
In order to promote GSoC and community activities,
we want to spend some of the budget on travel grants and other such promotional programs.
Due to time constraints,
travel grants need to be approved in a short timeframe in mid-summer.
It is a vacation period, and it is difficult to reach out to stakeholders and get approvals during this timeframe.

Having a separate GSoC budget and approval policy would
give more freedom to Jenkins GSoC Org Admins in order
to focus on organizational side of GSoC project.

== Reasoning

=== Guarantee letters

As stated above, Jenkins project and SPI cannot issue expense guarantee letters to students.
Unfortunately, we do not have other way available.
Should students need such guarantee letters for visa applications,
they should reach out to mentors or org admins.
There are several possible options:

* Mentors or Org Admins can issue personal guarantee letters for students
and provide personal bank statements.
In such case mentors will be personally liable for expense coverage,
including unexpected expenses
* GSoC student or his relatives may issue guarantee letters on their own.
In such case they will be personally responsible to cover travel expenses,
including unexpected ones
* An event organizer (company or individual) may issue a guarantee letter

All options above are not ideal,
but in the current state Jenkins project cannot offer other options.
The approach will be revisited when (and if) Jenkins project has a legal entity.

== Security

N/A (process JEP)

== Infrastructure Requirements

N/A (process JEP)

== Testing

N/A (process JEP)

== Prototype Implementation

N/A (process JEP)

== References

* http://jenkins.io/projects/gsoc/
* https://developers.google.com/open-source/gsoc/help/org-payments
* https://www.spi-inc.org/
* https://wiki.jenkins.io/display/JENKINS/Reimbursement+of+Expenses+via+SPI
