= JEP-0000: Evergreen Update Client/Server Lifecycle
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| JEP
| 0000

| Title
| Evergreen Update Client/Server Lifecycle

| Sponsor
| link:https://github.com/rtyler[R. Tyler Croy]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Standards

| Created
| 2018-04-17
//
//
// Uncomment if there is an associated placeholder JIRA issue.
//| JIRA
//| :bulb: https://issues.jenkins-ci.org/browse/JENKINS-nnnnn[JENKINS-nnnnn] :bulb:
//
//
// Uncomment if there will be a BDFL delegate for this JEP.
//| BDFL-Delegate
//| :bulb: Link to github user page :bulb:
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
| Requires
| JEP-300, JEP-303
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

Integral to link:https://github.com/jenkinsci/jep/tree/master/jep/300[Jenkins
Essentials] is the client's update lifecycle with the Evergreen hosted service
layer. Starting for the first boot, the client must frequently inform the
client of its current versions, retrieve new versions, and apply updates. This
document specifies those API interactions and expectations to allow this update
lifecycle to be performed correctly.

== Specification

The role of the versions service is simply to maintain an audit trail of sorts
for the versions of sofware that each client has installed locally.


The role of the update service is to use the `essentials.yaml` and retriev the
latest versions of software for a given client UUID and compute the appropriate
update response by the client

.Bootstrapping Instance
[source]
----

  update                     versions                    evergreen
  service                    service                      client
     |                           |                           |
     |                           |     POST version manifest |
     |                           |     from local hpis/core  |
     |                           |<--------------------------o
     |                           o-----------/ok/----------->|
     |                           |                           |
     |                     GET /update                       |
     |<------------------------------------------------------o
     |    GET /versions for uuid |                           |
     o-------------------------->|                           |
     |<-----/200 json payload/---o                           |
     |                           |                           |
     |                 200 with computed JSON payload        |
     |                 indicating what files should          |
     |                 be downloaded                         |
     o------------------------------------------------------>|
     |                           |                           |
----

== Motivation

[TIP]
====
Explain why the existing code base or process is inadequate to address the problem that the JEP solves.
====

== Reasoning

[TIP]
====
Explain why particular design decisions were made.
Describe alternate designs that were considered and related work, e.g. how the feature is supported in other systems.
Provide evidence of consensus within the community and discuss important objections or concerns raised during discussion.
====

== Backwards Compatibility

[TIP]
====
Describe any incompatibilities and their severity.
Describe how the JEP proposes to deal with these incompatibilities.
If there are no backwards compatibility concerns, this section may simply say:
There are no backwards compatibility concerns related to this proposal.
====

== Security

[TIP]
====
Describe the security impact of this proposal.
Outline what was done to identify and evaluate security issues,
discuss of potential security issues and how they are mitigated or prevented,
and how the JEP interacts with existing permissions, authentication, authorization, etc.
If this proposal will have no impact on security, this section may simply say:
There are no security risks related to this proposal.
====

== Infrastructure Requirements

[TIP]
====
Describing any impact on Jenkins project infrastructure.

Include any additions or changes, interactions with exiting components,
potential instabilities, service-level agreements,
and responsibilities for continuing maintenance.
Explain the scope of infrastructure changes with sufficient detail
to allow initial and on-going cost (in both time and money) to be estimated.
If this proposal will have no impact on infrastructure, this section may simply say:
There are no new infrastructure requirements related to this proposal.
====

== Testing

[TIP]
====
If the JEP involves any kind of behavioral change to code
(whether in a Jenkins product or backend infrastructure),
give a summary of how its correctness (and, if applicable, compatibility, security, etc.) can be tested.

In the preferred case that automated tests can be developed to cover all significant changes, simply give a short summary of the nature of these tests.

If some or all of changes will require human interaction to verify, explain why automated tests are considered impractical.
Then summarize what kinds of test cases might be required: user scenarios with action steps and expected outcomes.
Might behavior vary by platform (operating system, servlet container, web browser, etc.)?
Are there foreseeable interactions between different permissible versions of components (Jenkins core, plugins, etc.)?
Are any special tools, proprietary software, or online service accounts required to exercise a related code path (Active Directory server, GitHub login, etc.)?
When will testing take place relative to merging code changes, and might retesting be required if other changes are made to this area in the future?

If this proposal requires no testing, this section may simply say:
There are no testing issues related to this proposal.
====

== Prototype Implementation

[TIP]
====
Link to any open source reference implementation of code changes for this proposal.
The reference implementation need not be completed before the JEP is <<accepted>>,
but must be completed before any JEP is given "Final" status.
JEPs which will not include code changes may omit this section.
====

== References

[TIP]
====
Provide links to any related documents.
====

[IMPORTANT]
====
When moving this JEP from a Draft to "Accepted" or "Final" state,
include links to the pull requests and mailing list discussions which were involved in the process.
====



