= JEP-0000: :bulb: Usage of JFrog Sponsored Repository :bulb:
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.**JEP Template**

.Metadata
[cols="1h,1"]
|===
| JEP
| 0000

| Title
| Usage of JFrog Sponsored Repository

| Sponsor
| link:https://github.com/dduportal

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Process

| Created
| 2022-09-19

| GitHub
| https://github.com/jenkins-infra/helpdesk/issues/2322

//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===

== Abstract

Realign the missions and goals of repo.jenkins-ci.org (JFrog SaaS-Hosted's Artifactory) to ensure its sustainability.

== Specification

=== TL;DR;

- Enable authentication on the repo.jenkins-ci.org mirrored repositories to limit who is able to download through our mirros
- Keep hosted repositories unauthenticated to keep a low contributing initial entry bar when building the Jenkins projects
- Add caching for our infrastructure build with full authenticated process

=== Proposal

[TIP]
====
Provide a detailed specification of what is being proposed.
Be as technical and detailed as needed to allow new or existing Jenkins developers
to reasonably understand the scope/impact of an implementation.

* Use present tense - describe what the proposal "does" (as if it were already done), not what it will do.
* Do not discuss alternative designs that were rejected - those belong in the Reasoning section.
* Avoid in-depth discussion or justification of design choices - that belongs in the Reasoning section.
====

== Motivation

Context: during the summer of 2022, the bandwidth usage of the JFrog Sponsored Artifactory SaaS instance (repo.jenkins-ci.org) is around 50 Tb per month.
JFrog ask the Jenkins project to decreased under 10 Tb per month (as per their Open Source programs) otherwise the project will be billed.

It's the opportunity to challenge and realign the missions of this service given its importance in the Jenkins project releases, security and infrastructure.

== Reasoning

=== Initial Missions

The missions of repo.jenkins-ci.org, as per the 2022 summer were:

- to host the artifacts produced by the Jenkins project from Open Source code (Core, plugins, sub projects), both
  - Public artifacts to be distributed for free
  - Private artifacts for link:https://www.jenkins.io/security/[Jenkins Security]
- to mirror upstream artifact repositories to ensure:
  - reproducibility of the Jenkins project builds
  - a good Quality of Service (QoS) when building Jenkins projects (as in "avoid slowing developers with unreliable external repositories")
- to aggregate mirrors and hosted repositories in a user friendly way for both Jenkins users ("public" repository for instance) and contributors ("incremental" repository for instance)

[IMPORTANT]
====
Authentication is required to read and write private repositories, and to write on public repositories.
It uses the Jenkins central LDAP authentication system.

It means that public artifacts can be downloaded anonymously.
====

=== Problem Statement

- The bandwidth usage of ~ 50 Tb / month looks really high, even for the Jenkins project.
- JFrog stated that the most probable cause for this usage is related to our (unauthenticated) mirror system which mirrors external repositories. It makes impossible to block any abusive or unfair downloads.
They recommend to only target the hosting Jenkins projects artifacts, or enable authenticated access to "know" who is consuming bandwidth.
- The ability to control and scan dependencies used by the Jenkins projects is a step forward in the supply chain security. Mirroring dependencies is a safety measure in this area.
- Quality of service when downloading dependencies had always been a concern, at least for ci.jenkins.io and Jenkins releases. Artifactory provides a really good service, but caching could help.

== Backwards Compatibility

[TIP]
====
Describe any incompatibilities and their severity.
Describe how the JEP proposes to deal with these incompatibilities.

If there are no backwards compatibility concerns, this section may simply say:
There are no backwards compatibility concerns related to this proposal.
====

== Security

[TIP]
====
Describe the security impact of this proposal.
Outline what was done to identify and evaluate security issues,
discuss potential security issues and how they are mitigated or prevented,
and detail how the JEP interacts with existing elements in Jenkins, such as permissions, authentication, authorization, etc.

If this proposal will have no impact on security, this section may simply say:
There are no security risks related to this proposal.
====

== Infrastructure Requirements

[TIP]
====
Describe any impact on the Jenkins project infrastructure.

Include any additions or changes, interactions with existing components,
potential instabilities, service-level agreements,
and responsibilities for continuing maintenance.
Explain the scope of infrastructure changes with sufficient detail
to allow initial and on-going cost (in both time and money) to be estimated.

If this proposal will have no impact on infrastructure, this section may simply say:
There are no new infrastructure requirements related to this proposal.
====

== Testing

[TIP]
====
If the JEP involves any kind of behavioral change to code
(whether in a Jenkins product or backend infrastructure),
give a summary of how its correctness (and, if applicable, compatibility, security, etc.) can be tested.

In the preferred case that automated tests can be developed to cover all significant changes, simply give a short summary of the nature of these tests.

If some or all of the changes will require human interaction to verify them, explain why automated tests are considered impractical.
Then, summarize what kinds of test cases might be required: user scenarios with action steps and expected outcomes.
Detail whether behavior might be different based on the platform (operating system, servlet container, web browser, etc.)?
Are there foreseeable interactions between different permissible versions of components (Jenkins core, plugins, etc.)?
Does this change require that any special tools, proprietary software, or online service accounts to exercise a related code path (e.g., Active Directory server, GitHub login, etc.)?
When will you complete testing relative to merging code changes, and might retesting be required if other changes are made to this area in the future?

If this proposal requires no testing, this section may simply say:
There are no testing issues related to this proposal.
====

== Prototype Implementation

[TIP]
====
Link to any open source reference implementation of code changes for this proposal.
The implementation need not be completed before the JEP is
link:https://github.com/jenkinsci/jep/tree/master/jep/1#accepted[accepted],
but must be completed before any JEP is given
"link:https://github.com/jenkinsci/jep/tree/master/jep/1#final[Final]" status.

JEPs which will not include code changes may omit this section.
====

== References

[TIP]
====
Provide links to any related documents.
This will include links to discussions on the mailing list, pull requests, and meeting notes.
====
