= JEP-0000: Replace Acegi Security with Spring Security & upgrade Spring Framework
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 0000

| Title
| Replace Acegi Security with Spring Security & upgrade Spring Framework

| Sponsor
| link:https://github.com/jglick[Jesse Glick]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Standards

| Created
| :bulb: Date (YYYY-MM-DD) :bulb:

| BDFL-Delegate
| TBD

| JIRA
| https://issues.jenkins-ci.org/browse/JENKINS-5303[JENKINS-5303]

// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===

== Abstract

[TIP]
====
Give a short (200 word) description of the technical issue addressed.

* Use present tense - describe what the proposal "does" (as if it were already done), not what it will do.
* Do not go into technical details and instead put those in the Specification section.
* Do not talk about history or why this needs to be done. Instead, add the history to the Motivation section.
====

== Specification

This work consists of several phases, both in Jenkins core and plugins.

* Classpath changes in Jenkins core:
** The actual Acegi Security JAR is removed from the classpath, replaced with Spring Security.
** All of Spring is updated to the current release (5.x).
** LDAP-specific classes are not readded.
* All of Jenkins core is switched to use Spring Security as its primary model.
* `org.acegisecurity.*` types are reintroduced only in cases where it seems there are a lot of plugins using them, using clean reimplementations.
** `Sid` and subtypes are for now simply reimplemented, rather than delegating to the `spring-security-acl` module.
** `toSpring` and `fromSpring` method are provided to interconvert Acegi Security and Spring Security types.
** Subtyping relationships are not used for most interfaces, but _are_ used for selected exception types.
** `org.springframework.dao.DataAccessException` is deprecated.
** Existing Jenkins API methods referring to `org.acegisecurity.*` types are retained where feasible but deprecated and bridged to new Spring Security equivalents.
* (TBD) A new simplified API is created to hide the details of Spring Security and cover the operations most commonly required by plugins:
** obtain current identity, whether a real person ~ `User` or `SYSTEM` or `ANONYMOUS` or an unidentified but authenticated person
** check password
** temporarily switch identity
** check permissions
* Some important plugins are made to compile and run against the resulting core version using some combination of:
** Replacing idioms which are already unnecessary (e.g., switch to `ACL.as`).
** Using the new simplified API.
** Expanding compatibility bridges in core.
* Ensuring compatibility for plugins implementing `SecurityRealm`, which are harder to deal with. These may simply require new releases built against Spring Security. Fortunately there are not that many of them: a few in regular use or previously bundled (`ldap`, `active-directory`, `reverse-proxy-auth-plugin`, `pam`, `github-oauth`, etc.) and some lesser-used ones (`crowd2`, `saml`, etc.).
* Making sure core plus all plugins mentioned in the setup wizard (even if not `suggested`) work together.
* Track status of other “long-tail” plugins and offer assistance to maintainers.

== Motivation

[TIP]
====
Explain why the existing code base or process is inadequate to address the problem that the JEP solves.
This section may also contain any historical context such as how things were done before this proposal.

* Do not discuss design choices or alternative designs that were rejected - those belong in the Reasoning section.
====

=== Technical debt

A lot of this code was written 13 years ago by Kohsule, has barely been touched since,
and involves heavy modifications to Acegi Security functionality,
in some cases apparently to work around limitations that may well have been addressed years ago in Spring Security.
Working with long-obsolete APIs is tricky due to lack of knowledge—the Spring Security maintainer may barely remember how things were.
The Jenkins CERT team has to examine code for vulnerabilities rather than relying on community knowledge in CVEs.

== Reasoning

[TIP]
====
Explain why particular design decisions were made.
Describe alternate designs that were considered and related work. For example, how the feature is supported in other systems.
Provide evidence of consensus within the community and discuss important objections or concerns raised during discussion.

* Use sub-headings to organize this section for ease of readability.
* Do not talk about history or why this needs to be done - that is part of Motivation section.
====

== Backwards Compatibility

[TIP]
====
Describe any incompatibilities and their severity.
Describe how the JEP proposes to deal with these incompatibilities.

If there are no backwards compatibility concerns, this section may simply say:
There are no backwards compatibility concerns related to this proposal.
====

== Security

[TIP]
====
Describe the security impact of this proposal.
Outline what was done to identify and evaluate security issues,
discuss potential security issues and how they are mitigated or prevented,
and detail how the JEP interacts with existing elements in Jenkins, such as permissions, authentication, authorization, etc.

If this proposal will have no impact on security, this section may simply say:
There are no security risks related to this proposal.
====

== Infrastructure Requirements

[TIP]
====
Describe any impact on the Jenkins project infrastructure.

Include any additions or changes, interactions with existing components,
potential instabilities, service-level agreements,
and responsibilities for continuing maintenance.
Explain the scope of infrastructure changes with sufficient detail
to allow initial and on-going cost (in both time and money) to be estimated.

If this proposal will have no impact on infrastructure, this section may simply say:
There are no new infrastructure requirements related to this proposal.
====

== Testing

[TIP]
====
If the JEP involves any kind of behavioral change to code
(whether in a Jenkins product or backend infrastructure),
give a summary of how its correctness (and, if applicable, compatibility, security, etc.) can be tested.

In the preferred case that automated tests can be developed to cover all significant changes, simply give a short summary of the nature of these tests.

If some or all of the changes will require human interaction to verify them, explain why automated tests are considered impractical.
Then, summarize what kinds of test cases might be required: user scenarios with action steps and expected outcomes.
Detail whether behavior might be different based on the platform (operating system, servlet container, web browser, etc.)?
Are there foreseeable interactions between different permissible versions of components (Jenkins core, plugins, etc.)?
Does this change require that any special tools, proprietary software, or online service accounts to exercise a related code path (e.g., Active Directory server, GitHub login, etc.)?
When will you complete testing relative to merging code changes, and might retesting be required if other changes are made to this area in the future?

If this proposal requires no testing, this section may simply say:
There are no testing issues related to this proposal.
====

== Prototype Implementation

* link:https://github.com/jenkinsci/jenkins/pull/4848[jenkins #4848]

== References

* Searching for usages of Acegi Security in plugins
** link:https://github.com/jenkins-infra/usage-in-plugins/pull/15[usage-in-plugins #15] (PoC by Wadeck)
** link:https://github.com/jenkins-infra/usage-in-plugins/pull/16[usage-in-plugins #16] (general improvement by jglick)
* Preparatory patches
** link:https://github.com/jenkinsci/reverse-proxy-auth-plugin/pull/38[reverse-proxy-auth-plugin #38] (cleanup by Wadeck)
** link:https://github.com/jenkinsci/authorize-project-plugin/pull/46[authorize-project-plugin #46] (cleanup by Wadeck)
* Exploratory work
** link:https://github.com/Wadeck/poc-acegi-security-facade-lib[poc-acegi-security-facade-lib] (PoC by Wadeck)
** link:https://github.com/jenkinsci/jenkins/pull/4844[jenkins #4844] (PoC by Wadeck)
* Reference implementation
** link:https://github.com/jenkinsci/jenkins/pull/4848[jenkins #4848] (upgrade to Spring Security 5 by jglick)
* Issues
** link:https://issues.jenkins-ci.org/browse/JENKINS-5303[JENKINS-5303] _Upgrade Acegi Security to the latest Spring Security release_
** link:https://issues.jenkins-ci.org/browse/JENKINS-49555[JENKINS-49555] _Split most of Spring Framework out of core_
* Miscellany
** link:https://github.com/jenkinsci/ldap-plugin/pull/17/files#r113542499[discussion in ldap-plugin #17] about supported configuration vs. Groovy bean bindings
* Tips on migrating between Spring Security versions
** https://dzone.com/articles/pathway-acegi-spring-security-[Acegi → 2] (unofficial)
** http://www.integratingstuff.com/2011/04/30/migrating-from-spring-security-2-to-spring-security-3/[2 → 3] (unofficial)
** link:https://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html[3 → 4] (official)
** link:https://github.com/spring-projects/spring-security/issues/4874[4 → 5] (requested)
