= JEP-0000: Evergreen Client Registration and Authentication
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| JEP
| 0000

| Title
| Evergreen Client Registration and Authentication

| Sponsor
| link:https://github.com/rtyler[R. Tyler Croy]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Standards

| Created
| 2018-03-21
//
//
| JIRA
| https://issues.jenkins-ci.org/browse/JENKINS-49810[JENKINS-49810], https://issues.jenkins-ci.org/browse/JENKINS-50347[JENKINS-50347]
//
// Uncomment if there will be a BDFL delegate for this JEP.
| BDFL-Delegate
| link:https://github.com/rtyler[R. Tyler Croy]
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
| Requires
| JEP-300
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

A major component of the
link:https://github.com/jenkinsci/jep/blob/master/jep/300[Jenkins Essentials]
initiative is the "connected-ness" of an instance. This entails sending
telemetry and receiving updates from the Evergreen hosted services layer. In
order to safely, and correctly, provide these services, each instance must have
a unique **identity** and a means of truthfully conveying information to the
Evergreen hosted services layer.


== Specification

[CAUTION]
====
This specification is still in flux and should be considered a work in progress
until a prototype has been successfully demonstrated
====

This specification describes a *non-interactive* registration and
authentication mechanism to be performed by the `evergreen-client`, the reasons
why <<non-interactive>> is an important aspect of this proposal can be found
below.

The `evergreen-client` must _initiate_ the registration process by generating
link:https://nodejs.org/dist/latest-v9.x/docs/api/crypto.html#crypto_class_ecdh[ECDH]
public and private keys. Similar to SSH-based public/private key
authentication, the public key will be shared with the Evergreen hosted
services layer, while the private key must be maintained entirely confidential
and unique to that Jenkins Essentials instance.


Once the public/private key pair has been generated, the `evergreen-client`
must send a `registration` request which includes, but is not limited to, the
public key. The Registration Service's responsibility is to persist the
client's public key, generate a new UUID footnoteref:[uuid, https://en.wikipedia.org/wiki/Uuid],
and return the UUID to the client.


Once this exchange has successfully completed, the client should be in a
"registered" state.


[reg-diagram]
.Registration
[source]
----
               registration        status              evergreen
database         service           service              client
   |               |                  |                    |
   |               |                  |    <generate ECDH pub/priv keypair>
   |               |                  |                    |
   |               |     PUT with generated public key     |
   | store pub/key |<--------------------------------------o
   |   and uuid    |                  |                    |
   |<--------------o                  |                    |
   o-----/ok/----->|            HTTP 201 Created           |
   |               |          (respond with uuid)          |
   |               o-------------------------------------->|
   |               |                  |                    |
----


Clients in a registered state must log into the authentication service in order
to access any other resources in the Evergreen hosted service layer. A `login`
request consists of the UUID footnoteref:[uuid], signed by the client's private
key. This provides the Authentication Service enough information to verify that
the client is authentic.

Once the client has been deemed authentic, the Authentication Service will
generate a link:https://jwt.io[JSON Web Token] (JWT) which must be encrypted
with a pre-shared key (PSK), known to the other backend services, but not the
client. Additionally, JWT must contains a **14 day expiry** for the <<claims>>
contained within the token. Reasoning for <<jwt>> can be found below.

The client must include this encrypted JWT in subsequent HTTP requests under
the `Authorization` header.

[login-diagram]
.Login
[source]
----
              authentication       status              evergreen
database         service           service              client
   |               |                  |                    |
   |               |       PUT uuid signed by private key  |
   |    get uuid   |<--------------------------------------o
   |   and pubkey  |                  |                    |
   |<--------------o                  |                    |
   o-------------->|                  |                    |
   |       <verify signature>         |                    |
   |     <generate JWT enc token>     |                    |
   |               |            HTTP 200 Ok                |
   |               |         (respond with JWT)            |
   |               o-------------------------------------->|
   |               |                  |                    |
   |               |                  |    Status request  |
   |               |                  |      (with JWT)    |
   |               |                  |<-------------------o
   |               |                  |      HTTP 201      |
   |               |                  o------------------->|
   |               |                  |                    |
----

The generated JWTs are _expected_ to expiry, and the client must gracefully
handle expired tokens. In the case of an expired JWT, the client must repeat
the <<login-diagram, Login flow>> once again, before re-attempting its original
request.

The client should perform an exponential backoff if it is unable to
successfully repeat the Login flow in order to avoid client or service-side
errors leading to cascading failures.


[expiry-diagram]
.JWT Expiry
[source]
-----
              authentication       status              evergreen
database         service           service              client
   |               |                  |                    |
   |               |                  |    Status request  |
   |               |                  |      (with JWT)    |
   |               |                  |<-------------------o
   |               |                  |      HTTP 401      |
   |               |                  o------------------->|
   |               |                  |             <re-initiate login>
   |               |                  |                    |
   |               |       PUT uuid signed by private key  |
   |    get uuid   |<--------------------------------------o
   |   and pubkey  |                  |                    |
   |<--------------o                  |                    |
   o-------------->|                  |                    |
   |       <verify signature>         |                    |
   |     <generate JWT enc token>     |                    |
   |               |            HTTP 200 Ok                |
   |               |         (respond with JWT)            |
   |               o-------------------------------------->|
   |               |                  |                    |
   |               |                  |    Status request  |
   |               |                  |      (with JWT)    |
   |               |                  |<-------------------o
   |               |                  |      HTTP 401      |
   |               |                  o------------------->|
   |               |                  |                    |
-----

[claims]
=== Claims

JSON Web Tokens (JWT) include the notion of "claims" which indicate to the
backend services whether the client possessing the token is authorized to
access that particular service.

Within the scope of this document, the Authentication Service must include the
"default" claims expected for clients in the JWT.

In this specification there is not any specific claims included in the design,
service/client claims should be considered subject to future designs and
implementations.

=== Client Re-keying

This specification does not include a design for clients to re-key and
transition from an older to a newer key. Such as in the case of a vulnerability
disclosure, algorithm change, or for other reasons. This topic **must** be
discussed in a future JEP but is not considered within the scope of this
document.


== Motivation

The motivation for this design should be fairly self evident. The Evergreen
distribution system requires a means of uniquely identifying clients and
managing their interactions with the various backend services. Not only must
these clients be uniquely identified, it's important that clients cannot
maliciously, or accidentally forge requests, on behalf of other clients.


== Reasoning

Much of this design is influenced by large-scale Client/Service registration
and authentication systems familiar to the
link:https://github.com/rtyler[author]
from previous projects. A key goal in this design is to provide a secure means
of authentication, and avoid an Authentication Service becoming a single point
of failure in the backend services necessary to power the Evergreen
distribution system.

Some of the specific aspects of this design are discussed further below.


[non-interactive]
=== Non-interactive

* No user/password login for an administrator
* Ensures not-yet-setup instances are still included in the Evergreen
  distribution system

[jwt]
== JSON Web Tokens

link:https://jwt.io[JSON Web Tokens]
have a number of useful features, but by far the most useful feature of JWTs is
that they are *stateless*. This ensures that once the initial token negotiation
(see: <<login-diagram, the login diagram>>)
has completed, a JWT may be passed in _any_ subsequent service request without
requiring the involvement of the Authentication Service or the database which
stores UUIDs and public keys.

Of secondary importance with JWT is the concept of <<claims>>, which allow
different clients to be given differing levels of access control to the backend
services. This is expected to be more useful in later stages of development for
the Evergreen distribution system when clients using an "alpha" or "beta"
channel receive access to different backend services that more generally
available clients will not yet have access to.


=== JWT Expiry

* Good security hygiene
* Allows periodic adjustment in claims



=== Alternative Approaches

There were no substantial alternative approaches considered in the design of
this registration and authentication system. In order to remain
<<non-interactive>>, the notion of a Username/Password combination for
registration is functionally impractical, if not impossible.

The use of OpenSSH-based public/private keys was considered early on, during
the "whiteboard stage", but was quickly discarded due to general lack of
wide-spread library support when compared to <<jwt>>.


== Backwards Compatibility

There is no previous "Jenkins Essentials registration system" and therefore no
backwards compatibility concerns.


== Security


Securely registering and authenticating clients is the primary motivation and
consequence of this desig. This section is intentionally empty as security
concerns are manifest in all other sections of this document.


== Infrastructure Requirements

[TIP]
====
Describing any impact on Jenkins project infrastructure.

Include any additions or changes, interactions with exiting components,
potential instabilities, service-level agreements,
and responsibilities for continuing maintenance.
Explain the scope of infrastructure changes with sufficient detail
to allow initial and on-going cost (in both time and money) to be estimated.
If this proposal will have no impact on infrastructure, this section may simply say:
There are no new infrastructure requirements related to this proposal.
====

== Testing

[TIP]
====
If the JEP involves any kind of behavioral change to code
(whether in a Jenkins product or backend infrastructure),
give a summary of how its correctness (and, if applicable, compatibility, security, etc.) can be tested.

In the preferred case that automated tests can be developed to cover all significant changes, simply give a short summary of the nature of these tests.

If some or all of changes will require human interaction to verify, explain why automated tests are considered impractical.
Then summarize what kinds of test cases might be required: user scenarios with action steps and expected outcomes.
Might behavior vary by platform (operating system, servlet container, web browser, etc.)?
Are there foreseeable interactions between different permissible versions of components (Jenkins core, plugins, etc.)?
Are any special tools, proprietary software, or online service accounts required to exercise a related code path (Active Directory server, GitHub login, etc.)?
When will testing take place relative to merging code changes, and might retesting be required if other changes are made to this area in the future?

If this proposal requires no testing, this section may simply say:
There are no testing issues related to this proposal.
====

== Prototype Implementation

[TIP]
====
Link to any open source reference implementation of code changes for this proposal.
The reference implementation need not be completed before the JEP is <<accepted>>,
but must be completed before any JEP is given "Final" status.
JEPs which will not include code changes may omit this section.
====

== References

[TIP]
====
Provide links to any related documents.
====

[IMPORTANT]
====
When moving this JEP from a Draft to "Accepted" or "Final" state,
include links to the pull requests and mailing list discussions which were involved in the process.
====



