= JEP-0000: Modular Components
:toc: preamble
:toclevels: 3
:source-highlighter: highlightjs
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 0000

| Title
| Modular Components

| Sponsor
| https://github.com/sophistifunk

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted

| Type
| Standards

| Created
| 2018-08-08

| BDFL-Delegate
| TBD

//
//
// Uncomment if there is an associated placeholder JIRA issue.
//| JIRA
//| :bulb: https://issues.jenkins-ci.org/browse/JENKINS-nnnnn[JENKINS-nnnnn] :bulb:
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| :bulb: JEP-NUMBER, JEP-NUMBER... :bulb:
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===

== Abstract

This document describes a set of practices to allow creation and embedding of Modular UX Widgets: Compound React components that are more task-specific and self-contained than the simpler, building-block kind of components found in a common UI Component library package (such as Button, Table, DropDown, etc).

Example use cases:

* Pipeline run graph
* Pipeline creation wizard
* Pipeline activity table

== Specification

=== Embedding a Widget into a Host Application

==== Requirements

* A bundler/transpiler that understands ES6 Modules (or modern browser requirements)
* React 

Additionally, the Widget module artefact will include TypeScript `*.d.ts` files for Host Applications using TypeScript, but you are free to ignore them otherwise.  

==== Adding it to your project 

Add the Widget to your application's dependencies like a normal NPM module:

----
npm install --save @org-name/widget-module-name 
----

And render it as you would any other React component:

[source, JavaScript]
----
import { FooWidget } from '@org-name/widget-module-name';

class MyWrapper extends React.Component {

    /* .... */

    render() {
        /* .... */
        return (
            <div>
                <h1>Hello, World!</h1>
                <FooWidget foo="bar" baz={quux}/>
            </div>
        );
    }
}
----

==== Providing the Data Model

The data model should be provided to the Widget via React properties, as a normal JavaScript object: 

[source, JavaScript]
----
    render() {
        const topLevelStages = this.getTopLevelStages();
        return (
            <PipelineGraph stages={topLevelStages}/>
        );
    }
----

The expected type of all data model properties will be described in the Widget's documentation, as well as available in the form of TypeScript `Foo.d.ts` files in the artefact alongside the JavaScript source.

Unless specifically described otherwise in the Widget's documentation, treat data model objects as immutable, and do not expect the Widget to re-render if you change some of its nested properties.

==== Providing CSS

Each Widget will provide the styles it requires in a predictable location within the artefact:

* As CSS, located with the entry at `/styles/css/main.css`
* Optionally as SCSS source files with the entry at `/styles/scss/main.scss`

It is up to the Host Application to ensure that the correct styles are loaded when rendering the widget. How you do that depends on your Application's build process and environment.

==== Providing Static Assets

Any static assets (such as images) required by the Widget will be provided in the artefact within the `/assets/` folder, and must be set as React props on the Widget.

Host Applications can serve these assets from a known location and provide the HREFs to the widget:

[source, JavaScript]
----
    render() {
        const assetBase = this.getAssetBase();

        const assets = {
            happy: `${assetBase}/happy.png`,
            sad: `${assetBase}/sad.png`
        };

        return (
            <FaceWidget {...assets}/>
        );
    }
----

As an alternative, depending on your bundler/loader, you can embed them directly from the artefact as `data://` URLs:

[source, JavaScript]
----
const happyImg = require('@example-org/widget-module-name/assets/happy.png');
const sadImg = require('@example-org/widget-module-name/assets/happy.png');

class MyWrapper extends React.Component {

    /* .... */

    render() {
        const assets = {
            happy: happyImg,
            sad: sadImg
        };

        return (
            <FaceWidget {...assets}/>
        );
    }
}
----

==== Providing i18n Resources

Widgets will provide their localised resources as JSON in a predictable location:

* `/i18n/resources.en.json`
* `/i18n/resources.us.json`
* `/i18n/resources.jp.json`
* `/i18n/resources.de.json`
* _...etc_

The host application must, based on the user's current locale, provide the correct data to the Widget as a plain JavaScript object via the `resourceBundle` React prop.

If the host application supports locales for which the widget does not provide a bundle, default to `en`.

==== Providing Service Objects

In some instances, a Widget may require service objects to provide access to an API. These will be host-specific, and must be provided by the Host Application via React props.

The detailed interfaces that must be implemented by any service objects will be provided by the Widget's documentation, as well as in the form of TypeScript `*.d.ts` definitions in the Widget module artefact.

==== Listening to Widget Events

A Widget may provide standard React events via any number of `onFoo=` props that the Host Application can choose to listen to. The Widget's documentation will provide details of the meaning and function signiatures for any Widget Events, as well as in the form of TypeScript `*.d.ts` definitions in the Widget module artefact.

==== Notifying Widget of External Events

In some instances, a Widget will need to be notified about events from the Host Application or the outside world, in a way that would not be well served by changing a data model prop. For this purpose we use a simple implementation of the https://en.wikipedia.org/wiki/Signals_and_slots[Signal pattern]. The Widget Framework library contains the interface definitions and a simple implementation class that can be re-used by Host Applications:

[source, TypeScript]
----

import { EventSource } from 'widget-framework';

class App extends React.Component {

    // Signal instance
    fileChanged = new EventSource<String>('fileChanged');

    // Method called by some other code (not shown)
    externalFileChanged(filename: string) {
        // Notify the widget via our signal
        this.fileChanged.dispatch(filename);
    }

    render() {
        return (
            <DirectoryListingWidget fileChanged={this.fileChanged} />
        );
    }
}
----

=== Creating and Publishing a Widget

==== Requirements 

==== Good Documentation

==== Main Widget Class

==== Metadata

==== CSS

==== Static Assets

==== Internationalisation

==== Service Object Interfaces

==== Widget Events

==== Host Events

==== Building and Publishing your Widget

=== Widget Artefact Specifications

[TIP]
====
Provide a detailed specification what is being proposed.
Be as technical and detailed as needed to allow new or existing Jenkins developers
to reasonably understand the scope/impact of an implementation.

* Use present tense - describe what the proposal "does" (as if it were already done) not what it will do.
* Do not discuss alternative designs that were rejected, those belong in the Reasoning section.
* Avoid in-depth discussion or justification of design choices, that belongs in the Reasoning section.
====

== Motivation

In order to share existing React components with other projects, as well as improve flexibility and maintainability within the Blue Ocean project, we need a standard method for defining and documenting individual Widget modules, their responsibilities, and the responsibilities of the host application. Clearly marked module boundaries will help us keep code maintainable and testable, and should allow other projects more flexibility in picking and choosing the versions of Widget dependencies rather than the all-or-nothing approach required when depending on the current entire Blue Ocean Plugin.

[TIP]
====
Explain why the existing code base or process is inadequate to address the problem that the JEP solves.
This section may also contain any historal context such as how things were done before this proposal.

* Do not discuss design choices or alternative designs that were rejected, those belong in the Reasoning section.
====

== Reasoning

[TIP]
====
Explain why particular design decisions were made.
Describe alternate designs that were considered and related work, e.g. how the feature is supported in other systems.
Provide evidence of consensus within the community and discuss important objections or concerns raised during discussion.

* Use sub-headings to organize this section for ease of readability.
* Do not talk about history or why this needs to be done, that is part of Motivation section.
====

== Backwards Compatibility

There are no backwards compatibility concerns related to this proposal.

== Security

There are no security risks related to this proposal.

== Infrastructure Requirements

There are no new infrastructure requirements related to this proposal.

== Testing

Individual projects maintaining Widgets or host applications that rely on them will be responsible for the applicable testing infrastructure, although testability of existing code is expected to improve as these processes are adopted and components are extracted as Widgets.

== Prototype Implementation

https://github.com/sophistifunk/modular-ux-widgets-poc

== References

[TIP]
====
Provide links to any related documents.
This will include links to discussions on the mailing list, pull requests, and meeting notes.
====



