= JEP-0000: Evergreen Update Client/Server Lifecycle
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="2"]
|===
| JEP
| 0000

| Title
| Evergreen Update Client/Server Lifecycle

| Sponsor
| link:https://github.com/rtyler[R. Tyler Croy]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Not Submitted :information_source:

| Type
| Standards

| Created
| 2018-04-17
//
//
// Uncomment if there is an associated placeholder JIRA issue.
//| JIRA
//| :bulb: https://issues.jenkins-ci.org/browse/JENKINS-nnnnn[JENKINS-nnnnn] :bulb:
//
//
// Uncomment if there will be a BDFL delegate for this JEP.
//| BDFL-Delegate
//| :bulb: Link to github user page :bulb:
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
| Requires
| JEP-300, JEP-303
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

Integral to link:https://github.com/jenkinsci/jep/tree/master/jep/300[Jenkins
Essentials] is the client's update lifecycle with the Evergreen hosted service
layer. Starting for the first boot, the client must frequently inform the
client of its current versions, retrieve new versions, and apply updates. This
document specifies those API interactions and expectations to allow this update
lifecycle to be performed correctly.

== Specification

The role of the versions service is simply to maintain an audit trail of sorts
for the versions of software that each client has installed locally.


The role of the update service is to use the `essentials.yaml` and retrieve the
latest versions of software for a given client UUID and compute the appropriate
update response by the client

.Bootstrapping Instance
[source]
----

  update                     versions                    evergreen
  service                    service                      client
     |                           |                           |
     |                           |     POST version manifest |
     |                           |     from local hpis/core  |
     |                           |<--------------------------o
     |                           o-----------/ok/----------->|
     |                           |                           |
     |                     GET /update                       |
     |<------------------------------------------------------o
     |    GET /versions for uuid |                           |
     o-------------------------->|                           |
     |<-----/200 json payload/---o                           |
     |                           |                           |
     |            200 with computed JSON update manifest     |
     |            indicating what files should               |
     |            be downloaded                              |
     o------------------------------------------------------>|
     |                           |                           |
----

[[update-manifest]]
=== Update Manifest

The responses sent to the client must be well-formed JSON documents, referred
to as "update manifests" which the client must understand. The Update Manifest
should have a consistent structure but will be dynamically generated _per
client_ in order to ensure that the client is only downloading what is
necessary to update that specific client.

.Example Update Manifest
[source,json]
----
{
    "core" : {
        "uri" : "https://update-cdn.example.com/some/path/to/a/jenkins.war",
        "checksum" : {
            "type" : "sha256",
            "signature" : "somechecksumforthefile"
        }
    },
    "plugins" : {
        "updates" : [
            {
                "uri" : "https://update-cdn.example.com/some/path/to/a/plugin.hpi",
                "checksum" : {
                    "type" : "sha256",
                    "signature" : "somechecksumforthefile"
                }
            },
            {
                "uri" : "https://update-cdn.example.com/some/path/to/another/plugin.hpi",
                "checksum" : {
                    "type" : "sha256",
                    "signature" : "somechecksumforthefile"
                }
            }
        ]
    },
    "client" : {
        "uri" : "https://update-cdn.example.com/some/path/to/a/evergreen-client.tar.gz",
        "checksum" : {
            "type" : "sha256",
            "signature" : "somechecksumforthefile"
        }
    }
}
----

The three primary keys of the update manifest are:

* `core` which indicates that a new jenkins.war is necessary.
* `plugins` which will include a list of `updates` for plugins. This is an
  object within the JSON structure rather than a flat array as it is expected
  that at some point in the future we  may require a `removes` list to properly
  unpublish legacy or out-dated plugins from instances.
* `client` which indicates a new tarball for upgrading the `evergreen-client`
  itself.

Additional keys should be ignored by clients not supporting them to allow the
Update Manifest to safely include things which are not yet supported.

[NOTE]
====
There _may_ be opportunities to cache the Update Manifest in the future, but
this is considered a potential optimization which will be contingent on
observation of real world usage for Jenkins Essentials.
====


=== Client Update Behavior

The client should perform the necessary downloading of items
referenced in the <<update-manifest>> before initiating an client update
process, which is itself outside of the scope of this document.

The client should also update the "versions" service once an update has
successfully completed to ensure that subsequent checking in for updates
results in accurate manifests.


== Motivation

[TIP]
====
Explain why the existing code base or process is inadequate to address the problem that the JEP solves.
====

== Reasoning

[TIP]
====
Explain why particular design decisions were made.
Describe alternate designs that were considered and related work, e.g. how the feature is supported in other systems.
Provide evidence of consensus within the community and discuss important objections or concerns raised during discussion.
====

== Backwards Compatibility

Not necessary as there is no pre-existing implementation.

== Security


=== Update Manifest Authenticity

== Infrastructure Requirements

Nothing additional outside of the existing requirements already for the
Evergreen hosted service layer.

== Testing

Outside of the scope of this documentation

== Prototype Implementation


The prototype and _actual_ implementation of this work is being performed in
the link:https://github.com/jenkins-infra/evergreen[jenkins-infra/evergreen]
repository.

== References
