= JEP-5: Jenkins Ambassador Program
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


.Metadata
[cols="2"]
|===
| JEP
| 5

| Title
| Jenkins Ambassador Program

| Sponsor
| link:https://github.com/alyssat[Alyssa Tong], link:https://github.com/bitwiseman[Liam Newman]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Process

| Created
| 2018-05-02
//
//
// Uncomment if there is an associated placeholder JIRA issue.
//| JIRA
//| :bulb: https://issues.jenkins-ci.org/browse/JENKINS-nnnnn[JENKINS-nnnnn] :bulb:
//
//
// Uncomment if there will be a BDFL delegate for this JEP.
//| BDFL-Delegate
//| :bulb: Link to github user page :bulb:
//
//
// Uncomment if discussion will occur in forum other than jenkinsci-dev@ mailing list.
//| Discussions-To
//| :bulb: Link to where discussion and final status announcement will occur :bulb:
//
//
// Uncomment if this JEP depends on one or more other JEPs.
//| Requires
//| :bulb: JEP-NUMBER, JEP-NUMBER... :bulb:
//
//
// Uncomment and fill if this JEP is rendered obsolete by a later JEP
//| Superseded-By
//| :bulb: JEP-NUMBER :bulb:
//
//
// Uncomment when this JEP status is set to Accepted, Rejected or Withdrawn.
//| Resolution
//| :bulb: Link to relevant post in the jenkinsci-dev@ mailing list archives :bulb:

|===


== Abstract

Jenkins Ambassadors are influential Jenkins enthusiasts who have the passion to share their Jenkins technical expertise with others.
Ambassadors help to further the project by helping the community to understand how to use Jenkins and what makes Jenkins powerful.

This document describes the "Jenkins Ambassador" program,
including how the program will be governed, how Ambassadors are selected, and the duties and benefits of being a Jenkins Ambassador.

== Specification

=== Ambassador Program Goals

* Empower community leaders to talk, write, organize community building activities and or educate others about Jenkins.
* Cultivate the people whose efforts and commitment play an integral part in the growth of the Jenkins platform.
* Develop productive relationships with users and contributors

=== What is a Jenkins Ambassador?

A Jenkins Ambassador is a distinction that Jenkins awards key members of the community, similar to
link:https://www.docker.com/docker-captains[Docker Captain] or
link:https://community.oracle.com/docs/DOC-922857[Java Champion].
They are experts in one or more areas related to Jenkins are passionate about sharing their Jenkins knowledge with others.
Jenkins Ambassadors are volunteer representatives (not employees), leaders in the Jenkins community committed to sharing their Jenkins expertise.
No matter how they contribute -
whether they are blogging, writing books, speaking, creating tutorials and classes,
offering support in forums, or organizing and contributing to JAMs and other events –
they help make Jenkins better.


=== Benefits to Ambassador

* Recognition via jenkins.io
* “Ambassador” blog highlighting their accomplishments
* Free ticket to Jenkins World, JUC Israel
* Free access to Jenkins certification courses offered by CloudBees
* Special Ambassador gift

=== Responsiblities of Ambassadors

Jenkins Ambassador minimum responsibilities include at least 2 of the following items:

* Publish 3 or more blog posts on jenkins.io
* Give 3 or more Jenkins public presentations
* Organize 4 or more Jenkins events

Ambassadors must always adhere to the the
link:https://jenkins.io/project/conduct/[Jenkins Code of Conduct].

Additional responsiblities include the following:

* Provide feedback, ideas, and direction that will help to improve the Jenkins project.
  This involvement may be in the form of technical discussions, contributor summits,
  and or community building events/activities.
* Run workshops, develop or contribute to the development of tutorials, participate in
  and/or organize local events.
* Staff Jenkins World "Ask the Experts" booth or Jenkins booths at other events such as FOSDEM and ScaLE.


=== Nomination

Those who wish to become Jenkins Ambassadors may nominate themselves by filling out the
link:https://docs.google.com/forms/d/e/1FAIpQLSfswl1auVMC_ay0Y2xMw70tKK2j2IQevtGVSV9I0SQWbXW7mQ/viewform[Jenkins Ambassador Application]
form listing their qualifications.
The Events Officer or other board members may invite people to apply but the form will still need to be completed.

=== Acceptance

Jenkins Ambassador membership will be granted based on the consensus of the Jenkins Board members and officers.
Meeting the minimum requirements does not guarantee that an application will be accepted, but applications that meet the requirements will not be rejected without an explanation.

=== Term

Jenkins Ambassador memberships are annual positions.
Current Ambassadors' accomplishments will be reviewed each year to reconfirm their Jenkins Ambassador membership.
There is no set limit on the number of Jenkins Ambassadors.

=== Relationship to CloudBees

The Jenkins Ambassador program is Jenkins Community program sponsored by CloudBees.
However, the program is not a CloudBees promotional program.
Care will be taken to avoid CloudBees favoritism or even the appearance of such.
CloudBees employees may be Ambassadors.
There is no set limit to the number or percentage of CB employees that can be Ambassadors
(however, see avoiding favoritism above).

== Motivation

With the establishment of Jenkins Area meetup (JAMs),
the Jenkins community has grown vastly all over the world.
This growth has brought together novice, intermediate, to advanced users.
Each level of users has a unique need for Jenkins knowledge
and there aren’t enough Jenkins ‘educators’.
The document creates a program foster a stronger Jenkins community by recognizing
contributors that are both experts in one or more topics related to Jenkins
and active members of the community who make the effort to help the community.

== Reasoning

=== No hard limit on CloudBees employees

A hard limit of 10% or less are CB employees was considered,
but rejected due to concerns about fairness and added complexity.

=== Naming

A number of other names were considered for this program:

* Jenkins Steward
* Jenkins Advocate
* Jenkins Special Agent
* Jenkins Prefect

It was determined that these other names each had issues that made them less acceptable than "Jenkins Ambassador".
"Jenkins Special Agent" is too cutesy.
"Jenkins Steward" and "Jenkins Prefect" were a bit esoteric.
"Jenkins Advocate" would also work, but was kept in reserve for a future program.

=== Voting

We decided against having ambassadors voting for or against the addition of other ambassadors.
This would reduce the sense of team and community in among members.
Voting could also result in cliques and exlusionary behavior.
Having a clear set of guidelines and final approval made by the Jenkins Events Officer and Board members
seemed fairer and less prone to issues.

== Backwards Compatibility

There are no backwards compatibility concerns related to this proposal.

== Security

There are no security risks related to this proposal.

== Infrastructure Requirements

There are no new infrastructure requirements related to this proposal.

== Testing

There are no testing issues related to this proposal.

== References

* link:https://wiki.jenkins.io/display/JENKINS/Jenkins+Ambassador[Original Proposal from 2017]
* link:https://groups.google.com/d/topic/jenkinsci-dev/12D2tWxO6mM/discussion[jenkinsci-dev@ discussion]
* link:https://docs.google.com/forms/d/e/1FAIpQLSfswl1auVMC_ay0Y2xMw70tKK2j2IQevtGVSV9I0SQWbXW7mQ/viewform[Jenkins Ambassador Application]




