= JEP-216: Localization Plugin
:toc: preamble
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.Metadata
[cols="1h,1"]
|===
| JEP
| 216

| Title
| Localization Plugin

| Sponsor
| link:https://github.com/LinuxSuRen[Zhao Xiaojie]

// Use the script `set-jep-status <jep-number> <status>` to update the status.
| Status
| Draft :speech_balloon:

| Type
| Informational

| Created
| 2018-08-28

| BDFL-Delegate
| TBD

|===

== Abstract

At first, all languages files were aggregated in one place. There are some drawbacks that we need to improve.

Localization plugins separate i10n resource files from Jenkins core and plugins. This solution could
provide a way to let more native speakers can contribute localization more efficiently. Also for a single
Jenkins running instance does not need to load all languages files in most of the case.

== Specification

This propose suggest all languages have their own localization plugin. Such as link:https://github.com/jenkinsci/localization-zh-cn-plugin[Chinese Localization plugin].

In order to keep all languages plugins have the same style. There are some conventions need to follow.

Basically, all localization files that in the plugin should keep the same structure. And everyone could follow the link:https://wiki.jenkins.io/display/JENKINS/Internationalization[guide] to do the contribution. 

Localization plugin naming convention: localization-[language code]-[conuntry code]-plugin。You could add more
hunman-readable information in file `pom.xml`. For example `<name>Localization: Chinese (Simplified)</name>`。

You should add link:https://github.com/daniel-beck/localization-support-plugin[Localization Support Plugin] as a
dependency. Please don't add more dependencies if you haven't a strong reason. We need to keep the localization plugin as
simple as possible. There's an extension point(`LocalizationContributor`) needs to implement. There's only one language
is allowing. But you can add different variants if the contributors think it's ok.

There are some points need to translation:

* Localization from Jelly/Groovy views
* Localization from Java source codes
* Localization from help files
* Localization from JavaScript files

== Motivation

Localization plugin is targeted on Jenkins plugin developers who want to improve native language UI experience.
Let Jenkins is more easy to use.

== Reasoning

Easy for localization contribution access managing.
There is someone want to contribute localization, but he may not have the permission to commit, and other people perhaps can't do a real review. So this progress could be very slow.

== Backwards Compatibility

Remain all language files, until target language already moved into one localization plugin.

In order to give a great experience when a first installation is going. All localization files should be kept
which in the install wizard. And all language localization plugins will present in the language category of suggestion plugins.

In order to keep well compatibility between different versions, you can add a specific version directory.
For example, there is a help text for a button in ver 1.0, but it has a totally different meaning in ver 2.0.
In this case, you can create two directories to store translation files.
The language plugin should choose the right language files by the current version.
Actually, the language plugin should always try to find current version language files first, if it doesn't exist then use the latest one.
Maybe in most of the case, we just need to maintain the latest version.

There are some issues could arise in the progress of translation, such as wrong or stale translations. For help files, we
should provide a way to switch two versions between English and specific language.

In a common situation, we keep the latest version for translation in the localization plugin. But it's necessary to keep different versions in the plugin. And the plugin should provide a way to switch them.

Mininum support Jenkins core version is `2.151-20181111.210424-1`.

[WARNING]
====
*(linuxsuren)*
The feature that we needs is working in progress. Change the Jenkins core version later.
====

== Security

There are no security risks related to this proposal.

== Infrastructure Requirements

There are no new infrastructure requirements related to this proposal.

== Testing

Add junit test case to make sure that only specific language files could be placed in the plugin. For example,
all files should contain `zh-cn` in `localization-zh-cn-plugin`.

== Prototype Implementation

link:https://github.com/jenkinsci/localization-zh-cn-plugin[Localization: Chinese (Simplified)]
link:https://github.com/daniel-beck/localization-support-plugin[Localization Support Plugin]

== References

* link:https://groups.google.com/forum/#!msg/jenkinsci-dev/jeKVskUwE8M/gckewoBpDwAJ[Initial discussion]
* link:https://groups.google.com/forum/#!topic/jenkinsci-dev/8hA5x_CKB9c[Localization plugins: Where do we go from here?]
* link:https://jenkins.io/sigs/chinese-localization/[Chinese Localization SIG]
